// ============================================================================
//
// Copyright (c) 2006-2013, Talend Inc.
//
// This source code has been automatically generated by_Talend Open Studio for Data Integration
// / Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package islabs_mvmetrics.ga_iterate_profile_2_poplate_initial_client_data_0_2;

import routines.ConnectionUtil;
import routines.seomoz_common;
import routines.Mathematical;
import routines.LinksConstants;
import routines.LinksService;
import routines.string_to_date;
import routines.StringHandling;
import routines.Relational;
import routines.Authenticator;
import routines.islabs_common;
import routines.TalendString;
import routines.Numeric;
import routines.DataOperation;
import routines.Base64;
import routines.TalendDate;
import routines.TalendDataGenerator;
import routines.LinksResponse;
import routines.system.*;
import routines.system.api.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.util.Comparator;

//the import part of tJava_1
//import java.util.List;

@SuppressWarnings("unused")
/**
 * Job: ga_iterate_profile_2_poplate_initial_client_data Purpose: <br>
 * Description:  <br>
 * @author 
 * @version 5.3.1.r104014
 * @status 
 */
public class ga_iterate_profile_2_poplate_initial_client_data implements
		TalendJob {

	public final Object obj = new Object();

	// for transmiting parameters purpose
	private Object valueObject = null;

	public Object getValueObject() {
		return this.valueObject;
	}

	public void setValueObject(Object valueObject) {
		this.valueObject = valueObject;
	}

	private final static String defaultCharset = java.nio.charset.Charset
			.defaultCharset().name();

	private final static String utf8Charset = "UTF-8";

	// create and load default properties
	private java.util.Properties defaultProps = new java.util.Properties();

	// create application properties with default
	public class ContextProperties extends java.util.Properties {

		private static final long serialVersionUID = 1L;

		public ContextProperties(java.util.Properties properties) {
			super(properties);
		}

		public ContextProperties() {
			super();
		}

		public void synchronizeContext() {

			if (DB_HOST != null) {

				this.setProperty("DB_HOST", DB_HOST.toString());

			}

			if (DB_PORT != null) {

				this.setProperty("DB_PORT", DB_PORT.toString());

			}

			if (DB_SCHEMA != null) {

				this.setProperty("DB_SCHEMA", DB_SCHEMA.toString());

			}

			if (DB_USERNAME != null) {

				this.setProperty("DB_USERNAME", DB_USERNAME.toString());

			}

			if (DB_PASSWORD != null) {

				this.setProperty("DB_PASSWORD", DB_PASSWORD.toString());

			}

			if (DB_DBNAME != null) {

				this.setProperty("DB_DBNAME", DB_DBNAME.toString());

			}

			if (LOG_DIR_PATH != null) {

				this.setProperty("LOG_DIR_PATH", LOG_DIR_PATH.toString());

			}

			if (CURRENT_DATE != null) {

				this.setProperty("CURRENT_DATE", CURRENT_DATE.toString());

			}

			if (START_DATE != null) {

				this.setProperty("START_DATE", START_DATE.toString());

			}

			if (END_DATE != null) {

				this.setProperty("END_DATE", END_DATE.toString());

			}

			if (LAST_N_DAYS != null) {

				this.setProperty("LAST_N_DAYS", LAST_N_DAYS.toString());

			}

			if (SERVICE_ACCOUNT != null) {

				this.setProperty("SERVICE_ACCOUNT", SERVICE_ACCOUNT.toString());

			}

			if (KEY_FILE != null) {

				this.setProperty("KEY_FILE", KEY_FILE.toString());

			}

			if (PROFILE_ID != null) {

				this.setProperty("PROFILE_ID", PROFILE_ID.toString());

			}

			if (SMTP_PORT != null) {

				this.setProperty("SMTP_PORT", SMTP_PORT.toString());

			}

			if (SMTP_PASSWORD != null) {

				this.setProperty("SMTP_PASSWORD", SMTP_PASSWORD.toString());

			}

			if (SMTP_USERNAME != null) {

				this.setProperty("SMTP_USERNAME", SMTP_USERNAME.toString());

			}

			if (SMTP_SERVER != null) {

				this.setProperty("SMTP_SERVER", SMTP_SERVER.toString());

			}

			if (TEMP_DIR_PATH != null) {

				this.setProperty("TEMP_DIR_PATH", TEMP_DIR_PATH.toString());

			}

		}

		public String DB_HOST;

		public String getDB_HOST() {
			return this.DB_HOST;
		}

		public String DB_PORT;

		public String getDB_PORT() {
			return this.DB_PORT;
		}

		public String DB_SCHEMA;

		public String getDB_SCHEMA() {
			return this.DB_SCHEMA;
		}

		public String DB_USERNAME;

		public String getDB_USERNAME() {
			return this.DB_USERNAME;
		}

		public String DB_PASSWORD;

		public String getDB_PASSWORD() {
			return this.DB_PASSWORD;
		}

		public String DB_DBNAME;

		public String getDB_DBNAME() {
			return this.DB_DBNAME;
		}

		public String LOG_DIR_PATH;

		public String getLOG_DIR_PATH() {
			return this.LOG_DIR_PATH;
		}

		public String CURRENT_DATE;

		public String getCURRENT_DATE() {
			return this.CURRENT_DATE;
		}

		public String START_DATE;

		public String getSTART_DATE() {
			return this.START_DATE;
		}

		public String END_DATE;

		public String getEND_DATE() {
			return this.END_DATE;
		}

		public Integer LAST_N_DAYS;

		public Integer getLAST_N_DAYS() {
			return this.LAST_N_DAYS;
		}

		public String SERVICE_ACCOUNT;

		public String getSERVICE_ACCOUNT() {
			return this.SERVICE_ACCOUNT;
		}

		public String KEY_FILE;

		public String getKEY_FILE() {
			return this.KEY_FILE;
		}

		public Integer PROFILE_ID;

		public Integer getPROFILE_ID() {
			return this.PROFILE_ID;
		}

		public String SMTP_PORT;

		public String getSMTP_PORT() {
			return this.SMTP_PORT;
		}

		public String SMTP_PASSWORD;

		public String getSMTP_PASSWORD() {
			return this.SMTP_PASSWORD;
		}

		public String SMTP_USERNAME;

		public String getSMTP_USERNAME() {
			return this.SMTP_USERNAME;
		}

		public String SMTP_SERVER;

		public String getSMTP_SERVER() {
			return this.SMTP_SERVER;
		}

		public String TEMP_DIR_PATH;

		public String getTEMP_DIR_PATH() {
			return this.TEMP_DIR_PATH;
		}
	}

	private ContextProperties context = new ContextProperties();

	public ContextProperties getContext() {
		return this.context;
	}

	private final String jobVersion = "0.2";
	private final String jobName = "ga_iterate_profile_2_poplate_initial_client_data";
	private final String projectName = "ISLABS_MVMETRICS";
	public Integer errorCode = null;
	private String currentComponent = "";
	private final java.util.Map<String, Long> start_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Long> end_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Boolean> ok_Hash = new java.util.HashMap<String, Boolean>();
	private final java.util.Map<String, Object> globalMap = new java.util.HashMap<String, Object>();
	public final java.util.List<String[]> globalBuffer = new java.util.ArrayList<String[]>();

	public boolean isExportedAsOSGI = false;

	// OSGi DataSource
	private final static String KEY_DB_DATASOURCES = "KEY_DB_DATASOURCES";

	public void setDataSources(
			java.util.Map<String, javax.sql.DataSource> dataSources) {
		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		for (java.util.Map.Entry<String, javax.sql.DataSource> dataSourceEntry : dataSources
				.entrySet()) {
			talendDataSources.put(
					dataSourceEntry.getKey(),
					new routines.system.TalendDataSource(dataSourceEntry
							.getValue()));
		}
		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
	}

	LogCatcherUtils tLogCatcher_1 = new LogCatcherUtils();

	private final java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
	private final java.io.PrintStream errorMessagePS = new java.io.PrintStream(
			new java.io.BufferedOutputStream(baos));

	public String getExceptionStackTrace() {
		if ("failure".equals(this.getStatus())) {
			errorMessagePS.flush();
			return baos.toString();
		}
		return null;
	}

	private java.lang.Exception exception = null;

	public java.lang.Exception getException() {
		if ("failure".equals(this.getStatus())) {
			return this.exception;
		}
		return null;
	}

	private class TalendException extends java.lang.Exception {

		private static final long serialVersionUID = 1L;

		private java.util.Map<String, Object> globalMap = null;
		private java.lang.Exception e = null;
		private String currentComponent = null;

		private TalendException(java.lang.Exception e, String errorComponent,
				final java.util.Map<String, Object> globalMap) {
			this.currentComponent = errorComponent;
			this.globalMap = globalMap;
			this.e = e;
		}

		public java.lang.Exception getException() {
			return this.e;
		}

		public String getCurrentComponent() {
			return this.currentComponent;
		}

		@Override
		public void printStackTrace() {
			if (!(e instanceof TalendException || e instanceof TDieException)) {
				globalMap.put(currentComponent + "_ERROR_MESSAGE",
						e.getMessage());
				System.err
						.println("Exception in component " + currentComponent);
			}
			if (!(e instanceof TDieException)) {
				if (e instanceof TalendException) {
					e.printStackTrace();
				} else {
					e.printStackTrace();
					e.printStackTrace(errorMessagePS);
					ga_iterate_profile_2_poplate_initial_client_data.this.exception = e;
				}
			}
			if (!(e instanceof TalendException)) {
				try {
					for (java.lang.reflect.Method m : this.getClass()
							.getEnclosingClass().getMethods()) {
						if (m.getName().compareTo(currentComponent + "_error") == 0) {
							m.invoke(
									ga_iterate_profile_2_poplate_initial_client_data.this,
									new Object[] { e, currentComponent,
											globalMap });
							break;
						}
					}

					if (!(e instanceof TDieException)) {
						tLogCatcher_1.addMessage("Java Exception",
								currentComponent, 6, e.getClass().getName()
										+ ":" + e.getMessage(), 1);
						tLogCatcher_1Process(globalMap);
					}
				} catch (java.lang.SecurityException e) {
					this.e.printStackTrace();
				} catch (java.lang.IllegalArgumentException e) {
					this.e.printStackTrace();
				} catch (java.lang.IllegalAccessException e) {
					this.e.printStackTrace();
				} catch (java.lang.reflect.InvocationTargetException e) {
					this.e.printStackTrace();
				} catch (TalendException e) {
					// do nothing
				}

			}
		}
	}

	public void tLogCatcher_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tLogCatcher_1", System.currentTimeMillis());

		status = "failure";

		tLogCatcher_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tMap_2_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tMap_2", System.currentTimeMillis());

		status = "failure";

		tLogCatcher_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tFileOutputDelimited_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tFileOutputDelimited_1", System.currentTimeMillis());

		status = "failure";

		tLogCatcher_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tMysqlConnection_2_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tMysqlConnection_2", System.currentTimeMillis());

		status = "failure";

		tMysqlConnection_2_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tMysqlInput_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tMysqlInput_1", System.currentTimeMillis());

		status = "failure";

		tMysqlInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tBufferOutput_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tBufferOutput_1", System.currentTimeMillis());

		status = "failure";

		tMysqlInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tMysqlRow_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tMysqlRow_1", System.currentTimeMillis());

		status = "failure";

		tMysqlInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tMysqlCommit_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tMysqlCommit_1", System.currentTimeMillis());

		status = "failure";

		tMysqlCommit_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tBufferInput_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tBufferInput_1", System.currentTimeMillis());

		status = "failure";

		tBufferInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tFlowToIterate_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tFlowToIterate_1", System.currentTimeMillis());

		status = "failure";

		tBufferInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tRunJob_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tRunJob_1", System.currentTimeMillis());

		status = "failure";

		tBufferInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tPrejob_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tPrejob_1", System.currentTimeMillis());

		status = "failure";

		tPrejob_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tJava_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tJava_1", System.currentTimeMillis());

		status = "failure";

		tJava_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tLogCatcher_1_onSubJobError(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tMysqlConnection_2_onSubJobError(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tMysqlInput_1_onSubJobError(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tMysqlCommit_1_onSubJobError(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tBufferInput_1_onSubJobError(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tPrejob_1_onSubJobError(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tJava_1_onSubJobError(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public static class exceptionStruct implements
			routines.system.IPersistableRow<exceptionStruct> {
		final static byte[] commonByteArrayLock_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data = new byte[0];
		static byte[] commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data = new byte[0];

		public java.util.Date moment;

		public java.util.Date getMoment() {
			return this.moment;
		}

		public String job;

		public String getJob() {
			return this.job;
		}

		public String message;

		public String getMessage() {
			return this.message;
		}

		private java.util.Date readDate(ObjectInputStream dis)
				throws IOException {
			java.util.Date dateReturn = null;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				dateReturn = null;
			} else {
				dateReturn = new Date(dis.readLong());
			}
			return dateReturn;
		}

		private void writeDate(java.util.Date date1, ObjectOutputStream dos)
				throws IOException {
			if (date1 == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeLong(date1.getTime());
			}
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data.length) {
					if (length < 1024
							&& commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data.length == 0) {
						commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data = new byte[1024];
					} else {
						commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data = new byte[2 * length];
					}
				}
				dis.readFully(
						commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data,
						0, length);
				strReturn = new String(
						commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data,
						0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos)
				throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data) {

				try {

					int length = 0;

					this.moment = readDate(dis);

					this.job = readString(dis);

					this.message = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// java.util.Date

				writeDate(this.moment, dos);

				// String

				writeString(this.job, dos);

				// String

				writeString(this.message, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("moment=" + String.valueOf(moment));
			sb.append(",job=" + job);
			sb.append(",message=" + message);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(exceptionStruct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(),
						object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public static class row3Struct implements
			routines.system.IPersistableRow<row3Struct> {
		final static byte[] commonByteArrayLock_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data = new byte[0];
		static byte[] commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data = new byte[0];

		public java.util.Date moment;

		public java.util.Date getMoment() {
			return this.moment;
		}

		public String pid;

		public String getPid() {
			return this.pid;
		}

		public String root_pid;

		public String getRoot_pid() {
			return this.root_pid;
		}

		public String father_pid;

		public String getFather_pid() {
			return this.father_pid;
		}

		public String project;

		public String getProject() {
			return this.project;
		}

		public String job;

		public String getJob() {
			return this.job;
		}

		public String context;

		public String getContext() {
			return this.context;
		}

		public Integer priority;

		public Integer getPriority() {
			return this.priority;
		}

		public String type;

		public String getType() {
			return this.type;
		}

		public String origin;

		public String getOrigin() {
			return this.origin;
		}

		public String message;

		public String getMessage() {
			return this.message;
		}

		public Integer code;

		public Integer getCode() {
			return this.code;
		}

		private java.util.Date readDate(ObjectInputStream dis)
				throws IOException {
			java.util.Date dateReturn = null;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				dateReturn = null;
			} else {
				dateReturn = new Date(dis.readLong());
			}
			return dateReturn;
		}

		private void writeDate(java.util.Date date1, ObjectOutputStream dos)
				throws IOException {
			if (date1 == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeLong(date1.getTime());
			}
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data.length) {
					if (length < 1024
							&& commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data.length == 0) {
						commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data = new byte[1024];
					} else {
						commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data = new byte[2 * length];
					}
				}
				dis.readFully(
						commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data,
						0, length);
				strReturn = new String(
						commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data,
						0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos)
				throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		private Integer readInteger(ObjectInputStream dis) throws IOException {
			Integer intReturn;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				intReturn = null;
			} else {
				intReturn = dis.readInt();
			}
			return intReturn;
		}

		private void writeInteger(Integer intNum, ObjectOutputStream dos)
				throws IOException {
			if (intNum == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeInt(intNum);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data) {

				try {

					int length = 0;

					this.moment = readDate(dis);

					this.pid = readString(dis);

					this.root_pid = readString(dis);

					this.father_pid = readString(dis);

					this.project = readString(dis);

					this.job = readString(dis);

					this.context = readString(dis);

					this.priority = readInteger(dis);

					this.type = readString(dis);

					this.origin = readString(dis);

					this.message = readString(dis);

					this.code = readInteger(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// java.util.Date

				writeDate(this.moment, dos);

				// String

				writeString(this.pid, dos);

				// String

				writeString(this.root_pid, dos);

				// String

				writeString(this.father_pid, dos);

				// String

				writeString(this.project, dos);

				// String

				writeString(this.job, dos);

				// String

				writeString(this.context, dos);

				// Integer

				writeInteger(this.priority, dos);

				// String

				writeString(this.type, dos);

				// String

				writeString(this.origin, dos);

				// String

				writeString(this.message, dos);

				// Integer

				writeInteger(this.code, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("moment=" + String.valueOf(moment));
			sb.append(",pid=" + pid);
			sb.append(",root_pid=" + root_pid);
			sb.append(",father_pid=" + father_pid);
			sb.append(",project=" + project);
			sb.append(",job=" + job);
			sb.append(",context=" + context);
			sb.append(",priority=" + String.valueOf(priority));
			sb.append(",type=" + type);
			sb.append(",origin=" + origin);
			sb.append(",message=" + message);
			sb.append(",code=" + String.valueOf(code));
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row3Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(),
						object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void tLogCatcher_1Process(
			final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tLogCatcher_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";
		int iterateLoop = 0;
		String currentComponent = "";

		try {

			String currentMethodName = new java.lang.Exception()
					.getStackTrace()[0].getMethodName();
			boolean resumeIt = currentMethodName.equals(resumeEntryMethodName);
			if (resumeEntryMethodName == null || resumeIt || globalResumeTicket) {// start
																					// the
																					// resume
				globalResumeTicket = true;

				row3Struct row3 = new row3Struct();
				exceptionStruct exception = new exceptionStruct();

				/**
				 * [tFileOutputDelimited_1 begin ] start
				 */

				ok_Hash.put("tFileOutputDelimited_1", false);
				start_Hash.put("tFileOutputDelimited_1",
						System.currentTimeMillis());
				currentComponent = "tFileOutputDelimited_1";

				int tos_count_tFileOutputDelimited_1 = 0;

				String fileName_tFileOutputDelimited_1 = "";
				fileName_tFileOutputDelimited_1 = (new java.io.File(
						context.LOG_DIR_PATH + "populate_initial_data_"
								+ context.CURRENT_DATE + ".log"))
						.getAbsolutePath().replace("\\", "/");
				String fullName_tFileOutputDelimited_1 = null;
				String extension_tFileOutputDelimited_1 = null;
				String directory_tFileOutputDelimited_1 = null;
				if ((fileName_tFileOutputDelimited_1.indexOf("/") != -1)) {
					if (fileName_tFileOutputDelimited_1.lastIndexOf(".") < fileName_tFileOutputDelimited_1
							.lastIndexOf("/")) {
						fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1;
						extension_tFileOutputDelimited_1 = "";
					} else {
						fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
								.substring(0, fileName_tFileOutputDelimited_1
										.lastIndexOf("."));
						extension_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
								.substring(fileName_tFileOutputDelimited_1
										.lastIndexOf("."));
					}
					directory_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
							.substring(0, fileName_tFileOutputDelimited_1
									.lastIndexOf("/"));
				} else {
					if (fileName_tFileOutputDelimited_1.lastIndexOf(".") != -1) {
						fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
								.substring(0, fileName_tFileOutputDelimited_1
										.lastIndexOf("."));
						extension_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
								.substring(fileName_tFileOutputDelimited_1
										.lastIndexOf("."));
					} else {
						fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1;
						extension_tFileOutputDelimited_1 = "";
					}
					directory_tFileOutputDelimited_1 = "";
				}
				boolean isFileGenerated_tFileOutputDelimited_1 = true;
				java.io.File filetFileOutputDelimited_1 = new java.io.File(
						fileName_tFileOutputDelimited_1);
				globalMap.put("tFileOutputDelimited_1_FILE_NAME",
						fileName_tFileOutputDelimited_1);
				if (filetFileOutputDelimited_1.exists()) {
					isFileGenerated_tFileOutputDelimited_1 = false;
				}

				int nb_line_tFileOutputDelimited_1 = 0;
				int splitEvery_tFileOutputDelimited_1 = 1000;
				int splitedFileNo_tFileOutputDelimited_1 = 0;
				int currentRow_tFileOutputDelimited_1 = 0;

				final String OUT_DELIM_tFileOutputDelimited_1 = /**
				 * Start field
				 * tFileOutputDelimited_1:FIELDSEPARATOR
				 */
				";"/** End field tFileOutputDelimited_1:FIELDSEPARATOR */
				;

				final String OUT_DELIM_ROWSEP_tFileOutputDelimited_1 = /**
				 * Start
				 * field tFileOutputDelimited_1:ROWSEPARATOR
				 */
				"\n"/** End field tFileOutputDelimited_1:ROWSEPARATOR */
				;

				// create directory only if not exists
				if (directory_tFileOutputDelimited_1 != null
						&& directory_tFileOutputDelimited_1.trim().length() != 0) {
					java.io.File dir_tFileOutputDelimited_1 = new java.io.File(
							directory_tFileOutputDelimited_1);
					if (!dir_tFileOutputDelimited_1.exists()) {
						dir_tFileOutputDelimited_1.mkdirs();
					}
				}

				// routines.system.Row
				java.io.Writer outtFileOutputDelimited_1 = null;
				try {
					outtFileOutputDelimited_1 = new java.io.BufferedWriter(
							new java.io.OutputStreamWriter(
									new java.io.FileOutputStream(
											fileName_tFileOutputDelimited_1,
											true), "ISO-8859-15"));

					/**
					 * [tFileOutputDelimited_1 begin ] stop
					 */

					/**
					 * [tMap_2 begin ] start
					 */

					ok_Hash.put("tMap_2", false);
					start_Hash.put("tMap_2", System.currentTimeMillis());
					currentComponent = "tMap_2";

					int tos_count_tMap_2 = 0;

					// ###############################
					// # Lookup's keys initialization
					// ###############################

					// ###############################
					// # Vars initialization
					class Var__tMap_2__Struct {
					}
					Var__tMap_2__Struct Var__tMap_2 = new Var__tMap_2__Struct();
					// ###############################

					// ###############################
					// # Outputs initialization
					exceptionStruct exception_tmp = new exceptionStruct();
					// ###############################

					/**
					 * [tMap_2 begin ] stop
					 */

					/**
					 * [tLogCatcher_1 begin ] start
					 */

					ok_Hash.put("tLogCatcher_1", false);
					start_Hash.put("tLogCatcher_1", System.currentTimeMillis());
					currentComponent = "tLogCatcher_1";

					int tos_count_tLogCatcher_1 = 0;

					for (LogCatcherUtils.LogCatcherMessage lcm : tLogCatcher_1
							.getMessages()) {
						row3.type = lcm.getType();
						row3.origin = (lcm.getOrigin() == null
								|| lcm.getOrigin().length() < 1 ? null : lcm
								.getOrigin());
						row3.priority = lcm.getPriority();
						row3.message = lcm.getMessage();
						row3.code = lcm.getCode();

						row3.moment = java.util.Calendar.getInstance()
								.getTime();

						row3.pid = pid;
						row3.root_pid = rootPid;
						row3.father_pid = fatherPid;

						row3.project = projectName;
						row3.job = jobName;
						row3.context = contextStr;

						/**
						 * [tLogCatcher_1 begin ] stop
						 */
						/**
						 * [tLogCatcher_1 main ] start
						 */

						currentComponent = "tLogCatcher_1";

						tos_count_tLogCatcher_1++;

						/**
						 * [tLogCatcher_1 main ] stop
						 */

						/**
						 * [tMap_2 main ] start
						 */

						currentComponent = "tMap_2";

						boolean hasCasePrimitiveKeyWithNull_tMap_2 = false;

						// ###############################
						// # Input tables (lookups)
						boolean rejectedInnerJoin_tMap_2 = false;
						boolean mainRowRejected_tMap_2 = false;

						// ###############################
						{ // start of Var scope

							// ###############################
							// # Vars tables

							Var__tMap_2__Struct Var = Var__tMap_2;// ###############################
							// ###############################
							// # Output tables

							exception = null;

							// # Output table : 'exception'
							exception_tmp.moment = row3.moment;
							exception_tmp.job = row3.job;
							exception_tmp.message = row3.message;
							exception = exception_tmp;
							// ###############################

						} // end of Var scope

						rejectedInnerJoin_tMap_2 = false;

						tos_count_tMap_2++;

						/**
						 * [tMap_2 main ] stop
						 */
						// Start of branch "exception"
						if (exception != null) {

							/**
							 * [tFileOutputDelimited_1 main ] start
							 */

							currentComponent = "tFileOutputDelimited_1";

							StringBuilder sb_tFileOutputDelimited_1 = new StringBuilder();

							if (exception.moment != null) {

								sb_tFileOutputDelimited_1.append(

								FormatterUtils.format_Date(exception.moment,
										"yyyy-MM-dd HH:mm:ss")

								);

							}

							sb_tFileOutputDelimited_1
									.append(OUT_DELIM_tFileOutputDelimited_1);

							if (exception.job != null) {

								sb_tFileOutputDelimited_1.append(

								exception.job

								);

							}

							sb_tFileOutputDelimited_1
									.append(OUT_DELIM_tFileOutputDelimited_1);

							if (exception.message != null) {

								sb_tFileOutputDelimited_1.append(

								exception.message

								);

							}

							sb_tFileOutputDelimited_1
									.append(OUT_DELIM_ROWSEP_tFileOutputDelimited_1);

							nb_line_tFileOutputDelimited_1++;

							outtFileOutputDelimited_1
									.write(sb_tFileOutputDelimited_1.toString());

							tos_count_tFileOutputDelimited_1++;

							/**
							 * [tFileOutputDelimited_1 main ] stop
							 */

						} // End of branch "exception"

						/**
						 * [tLogCatcher_1 end ] start
						 */

						currentComponent = "tLogCatcher_1";

					}

					ok_Hash.put("tLogCatcher_1", true);
					end_Hash.put("tLogCatcher_1", System.currentTimeMillis());

					/**
					 * [tLogCatcher_1 end ] stop
					 */

					/**
					 * [tMap_2 end ] start
					 */

					currentComponent = "tMap_2";

					// ###############################
					// # Lookup hashes releasing
					// ###############################

					ok_Hash.put("tMap_2", true);
					end_Hash.put("tMap_2", System.currentTimeMillis());

					/**
					 * [tMap_2 end ] stop
					 */

					/**
					 * [tFileOutputDelimited_1 end ] start
					 */

					currentComponent = "tFileOutputDelimited_1";

				} finally {
					if (outtFileOutputDelimited_1 != null) {
						outtFileOutputDelimited_1.flush();
						outtFileOutputDelimited_1.close();
					}
					globalMap.put("tFileOutputDelimited_1_NB_LINE",
							nb_line_tFileOutputDelimited_1);
					globalMap.put("tFileOutputDelimited_1_FILE_NAME",
							fileName_tFileOutputDelimited_1);
				} // finally

				ok_Hash.put("tFileOutputDelimited_1", true);
				end_Hash.put("tFileOutputDelimited_1",
						System.currentTimeMillis());

				/**
				 * [tFileOutputDelimited_1 end ] stop
				 */

			}// end the resume

		} catch (java.lang.Exception e) {

			throw new TalendException(e, currentComponent, globalMap);

		} catch (java.lang.Error error) {

			throw error;

		}

		globalMap.put("tLogCatcher_1_SUBPROCESS_STATE", 1);
	}

	public void tMysqlConnection_2Process(
			final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tMysqlConnection_2_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";
		int iterateLoop = 0;
		String currentComponent = "";

		try {

			String currentMethodName = new java.lang.Exception()
					.getStackTrace()[0].getMethodName();
			boolean resumeIt = currentMethodName.equals(resumeEntryMethodName);
			if (resumeEntryMethodName == null || resumeIt || globalResumeTicket) {// start
																					// the
																					// resume
				globalResumeTicket = true;

				/**
				 * [tMysqlConnection_2 begin ] start
				 */

				ok_Hash.put("tMysqlConnection_2", false);
				start_Hash
						.put("tMysqlConnection_2", System.currentTimeMillis());
				currentComponent = "tMysqlConnection_2";

				int tos_count_tMysqlConnection_2 = 0;

				String properties_tMysqlConnection_2 = "noDatetimeStringSync=true";
				if (properties_tMysqlConnection_2 == null
						|| properties_tMysqlConnection_2.trim().length() == 0) {
					properties_tMysqlConnection_2 += "rewriteBatchedStatements=true";
				} else if (properties_tMysqlConnection_2 != null
						&& !properties_tMysqlConnection_2
								.contains("rewriteBatchedStatements")) {
					properties_tMysqlConnection_2 += "&rewriteBatchedStatements=true";
				}

				String url_tMysqlConnection_2 = "jdbc:mysql://"
						+ context.DB_HOST + ":" + context.DB_PORT + "/"
						+ context.DB_DBNAME + "?"
						+ properties_tMysqlConnection_2;

				String userName_tMysqlConnection_2 = context.DB_USERNAME;
				String password_tMysqlConnection_2 = context.DB_PASSWORD;

				java.sql.Connection conn_tMysqlConnection_2 = null;

				if ((null == globalMap.get(KEY_DB_DATASOURCES))
						|| "".equals("")) {

					java.lang.Class.forName("org.gjt.mm.mysql.Driver");

					conn_tMysqlConnection_2 = java.sql.DriverManager
							.getConnection(url_tMysqlConnection_2,
									userName_tMysqlConnection_2,
									password_tMysqlConnection_2);
					globalMap.put("conn_tMysqlConnection_2",
							conn_tMysqlConnection_2);
				}
				if (null != conn_tMysqlConnection_2) {

					conn_tMysqlConnection_2.setAutoCommit(false);
				}

				globalMap.put("conn_tMysqlConnection_2",
						conn_tMysqlConnection_2);

				globalMap.put("db_tMysqlConnection_2", context.DB_DBNAME);

				/**
				 * [tMysqlConnection_2 begin ] stop
				 */
				/**
				 * [tMysqlConnection_2 main ] start
				 */

				currentComponent = "tMysqlConnection_2";

				tos_count_tMysqlConnection_2++;

				/**
				 * [tMysqlConnection_2 main ] stop
				 */
				/**
				 * [tMysqlConnection_2 end ] start
				 */

				currentComponent = "tMysqlConnection_2";

				ok_Hash.put("tMysqlConnection_2", true);
				end_Hash.put("tMysqlConnection_2", System.currentTimeMillis());

				/**
				 * [tMysqlConnection_2 end ] stop
				 */

			}// end the resume

			if (resumeEntryMethodName == null || globalResumeTicket) {
				resumeUtil.addLog("CHECKPOINT",
						"CONNECTION:SUBJOB_OK:tMysqlConnection_2:OnSubjobOk",
						"", Thread.currentThread().getId() + "", "", "", "",
						"", "");
			}

			tMysqlInput_1Process(globalMap);

		} catch (java.lang.Exception e) {

			throw new TalendException(e, currentComponent, globalMap);

		} catch (java.lang.Error error) {

			throw error;

		}

		globalMap.put("tMysqlConnection_2_SUBPROCESS_STATE", 1);
	}

	public static class row2Struct implements
			routines.system.IPersistableRow<row2Struct> {
		final static byte[] commonByteArrayLock_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data = new byte[0];
		static byte[] commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data = new byte[0];

		public int jobid;

		public int getJobid() {
			return this.jobid;
		}

		public Integer profileid;

		public Integer getProfileid() {
			return this.profileid;
		}

		public Integer gaprofileid;

		public Integer getGaprofileid() {
			return this.gaprofileid;
		}

		private Integer readInteger(ObjectInputStream dis) throws IOException {
			Integer intReturn;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				intReturn = null;
			} else {
				intReturn = dis.readInt();
			}
			return intReturn;
		}

		private void writeInteger(Integer intNum, ObjectOutputStream dos)
				throws IOException {
			if (intNum == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeInt(intNum);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data) {

				try {

					int length = 0;

					this.jobid = dis.readInt();

					this.profileid = readInteger(dis);

					this.gaprofileid = readInteger(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// int

				dos.writeInt(this.jobid);

				// Integer

				writeInteger(this.profileid, dos);

				// Integer

				writeInteger(this.gaprofileid, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("jobid=" + String.valueOf(jobid));
			sb.append(",profileid=" + String.valueOf(profileid));
			sb.append(",gaprofileid=" + String.valueOf(gaprofileid));
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row2Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(),
						object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public static class row1Struct implements
			routines.system.IPersistableRow<row1Struct> {
		final static byte[] commonByteArrayLock_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data = new byte[0];
		static byte[] commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data = new byte[0];

		public int jobid;

		public int getJobid() {
			return this.jobid;
		}

		public Integer profileid;

		public Integer getProfileid() {
			return this.profileid;
		}

		public Integer gaprofileid;

		public Integer getGaprofileid() {
			return this.gaprofileid;
		}

		private Integer readInteger(ObjectInputStream dis) throws IOException {
			Integer intReturn;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				intReturn = null;
			} else {
				intReturn = dis.readInt();
			}
			return intReturn;
		}

		private void writeInteger(Integer intNum, ObjectOutputStream dos)
				throws IOException {
			if (intNum == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeInt(intNum);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data) {

				try {

					int length = 0;

					this.jobid = dis.readInt();

					this.profileid = readInteger(dis);

					this.gaprofileid = readInteger(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// int

				dos.writeInt(this.jobid);

				// Integer

				writeInteger(this.profileid, dos);

				// Integer

				writeInteger(this.gaprofileid, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("jobid=" + String.valueOf(jobid));
			sb.append(",profileid=" + String.valueOf(profileid));
			sb.append(",gaprofileid=" + String.valueOf(gaprofileid));
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row1Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(),
						object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void tMysqlInput_1Process(
			final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tMysqlInput_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";
		int iterateLoop = 0;
		String currentComponent = "";

		try {

			String currentMethodName = new java.lang.Exception()
					.getStackTrace()[0].getMethodName();
			boolean resumeIt = currentMethodName.equals(resumeEntryMethodName);
			if (resumeEntryMethodName == null || resumeIt || globalResumeTicket) {// start
																					// the
																					// resume
				globalResumeTicket = true;

				row1Struct row1 = new row1Struct();
				row1Struct row2 = row1;

				/**
				 * [tMysqlRow_1 begin ] start
				 */

				ok_Hash.put("tMysqlRow_1", false);
				start_Hash.put("tMysqlRow_1", System.currentTimeMillis());
				currentComponent = "tMysqlRow_1";

				int tos_count_tMysqlRow_1 = 0;

				java.sql.Connection conn_tMysqlRow_1 = null;
				conn_tMysqlRow_1 = (java.sql.Connection) globalMap
						.get("conn_tMysqlConnection_2");
				if (null == conn_tMysqlRow_1) {
					java.util.Map<String, routines.system.TalendDataSource> dataSources_tMysqlRow_1 = (java.util.Map<String, routines.system.TalendDataSource>) globalMap
							.get(KEY_DB_DATASOURCES);
					conn_tMysqlRow_1 = dataSources_tMysqlRow_1.get("")
							.getConnection();
				}

				java.sql.Statement stmt_tMysqlRow_1 = conn_tMysqlRow_1
						.createStatement();
				String query_tMysqlRow_1 = "";
				boolean whetherReject_tMysqlRow_1 = false;

				/**
				 * [tMysqlRow_1 begin ] stop
				 */

				/**
				 * [tBufferOutput_1 begin ] start
				 */

				ok_Hash.put("tBufferOutput_1", false);
				start_Hash.put("tBufferOutput_1", System.currentTimeMillis());
				currentComponent = "tBufferOutput_1";

				int tos_count_tBufferOutput_1 = 0;

				/**
				 * [tBufferOutput_1 begin ] stop
				 */

				/**
				 * [tMysqlInput_1 begin ] start
				 */

				ok_Hash.put("tMysqlInput_1", false);
				start_Hash.put("tMysqlInput_1", System.currentTimeMillis());
				currentComponent = "tMysqlInput_1";

				int tos_count_tMysqlInput_1 = 0;

				java.util.Calendar calendar_tMysqlInput_1 = java.util.Calendar
						.getInstance();
				calendar_tMysqlInput_1.set(0, 0, 0, 0, 0, 0);
				java.util.Date year0_tMysqlInput_1 = calendar_tMysqlInput_1
						.getTime();
				int nb_line_tMysqlInput_1 = 0;
				java.sql.Connection conn_tMysqlInput_1 = null;
				conn_tMysqlInput_1 = (java.sql.Connection) globalMap
						.get("conn_tMysqlConnection_2");
				if (null == conn_tMysqlInput_1) {
					java.util.Map<String, routines.system.TalendDataSource> dataSources_tMysqlInput_1 = (java.util.Map<String, routines.system.TalendDataSource>) globalMap
							.get(KEY_DB_DATASOURCES);
					conn_tMysqlInput_1 = dataSources_tMysqlInput_1.get("")
							.getConnection();
					// globalMap.put("conn_tMysqlConnection_2",
					// conn_tMysqlInput_1);
				}

				java.sql.Statement stmt_tMysqlInput_1 = conn_tMysqlInput_1
						.createStatement();

				String dbquery_tMysqlInput_1 = "SELECT    `initial_jobs_ga`.`jobid`,    `initial_jobs_ga`.`profileid`,    `initial_jobs_ga`.`gaprofileid` FROM `initial_jobs_ga` WHERE status='Ready' FOR UPDATE";

				globalMap.put("tMysqlInput_1_QUERY", dbquery_tMysqlInput_1);

				java.sql.ResultSet rs_tMysqlInput_1 = stmt_tMysqlInput_1
						.executeQuery(dbquery_tMysqlInput_1);
				java.sql.ResultSetMetaData rsmd_tMysqlInput_1 = rs_tMysqlInput_1
						.getMetaData();
				int colQtyInRs_tMysqlInput_1 = rsmd_tMysqlInput_1
						.getColumnCount();

				String tmpContent_tMysqlInput_1 = null;
				int column_index_tMysqlInput_1 = 1;
				while (rs_tMysqlInput_1.next()) {
					nb_line_tMysqlInput_1++;

					column_index_tMysqlInput_1 = 1;

					if (colQtyInRs_tMysqlInput_1 < column_index_tMysqlInput_1) {
						row1.jobid = 0;
					} else {

						if (rs_tMysqlInput_1
								.getObject(column_index_tMysqlInput_1) != null) {
							row1.jobid = rs_tMysqlInput_1
									.getInt(column_index_tMysqlInput_1);
						} else {
							throw new RuntimeException(
									"Null value in non-Nullable column");
						}

					}
					column_index_tMysqlInput_1 = 2;

					if (colQtyInRs_tMysqlInput_1 < column_index_tMysqlInput_1) {
						row1.profileid = null;
					} else {

						if (rs_tMysqlInput_1
								.getObject(column_index_tMysqlInput_1) != null) {
							row1.profileid = rs_tMysqlInput_1
									.getInt(column_index_tMysqlInput_1);
						} else {
							row1.profileid = null;
						}

					}
					column_index_tMysqlInput_1 = 3;

					if (colQtyInRs_tMysqlInput_1 < column_index_tMysqlInput_1) {
						row1.gaprofileid = null;
					} else {

						if (rs_tMysqlInput_1
								.getObject(column_index_tMysqlInput_1) != null) {
							row1.gaprofileid = rs_tMysqlInput_1
									.getInt(column_index_tMysqlInput_1);
						} else {
							row1.gaprofileid = null;
						}

					}

					/**
					 * [tMysqlInput_1 begin ] stop
					 */
					/**
					 * [tMysqlInput_1 main ] start
					 */

					currentComponent = "tMysqlInput_1";

					tos_count_tMysqlInput_1++;

					/**
					 * [tMysqlInput_1 main ] stop
					 */

					/**
					 * [tBufferOutput_1 main ] start
					 */

					currentComponent = "tBufferOutput_1";

					String[] row_tBufferOutput_1 = new String[] { "", "", "", };
					row_tBufferOutput_1[0] = String.valueOf(row1.jobid);

					if (row1.profileid != null) {

						row_tBufferOutput_1[1] = String.valueOf(row1.profileid);

					} else {
						row_tBufferOutput_1[1] = null;
					}
					if (row1.gaprofileid != null) {

						row_tBufferOutput_1[2] = String
								.valueOf(row1.gaprofileid);

					} else {
						row_tBufferOutput_1[2] = null;
					}
					globalBuffer.add(row_tBufferOutput_1);

					row2 = row1;

					tos_count_tBufferOutput_1++;

					/**
					 * [tBufferOutput_1 main ] stop
					 */

					/**
					 * [tMysqlRow_1 main ] start
					 */

					currentComponent = "tMysqlRow_1";

					query_tMysqlRow_1 = "UPDATE initial_jobs_ga SET status='Processing' WHERE jobid="
							+ row2.jobid
							+ " and profileid="
							+ row2.profileid
							+ " and gaprofileid= " + row2.gaprofileid;
					whetherReject_tMysqlRow_1 = false;

					globalMap.put("tMysqlRow_1_QUERY", query_tMysqlRow_1);
					try {
						stmt_tMysqlRow_1.execute(query_tMysqlRow_1);

					} catch (java.lang.Exception e) {
						whetherReject_tMysqlRow_1 = true;
						throw (e);
					}

					tos_count_tMysqlRow_1++;

					/**
					 * [tMysqlRow_1 main ] stop
					 */

					/**
					 * [tMysqlInput_1 end ] start
					 */

					currentComponent = "tMysqlInput_1";

				}
				rs_tMysqlInput_1.close();
				stmt_tMysqlInput_1.close();

				globalMap.put("tMysqlInput_1_NB_LINE", nb_line_tMysqlInput_1);

				ok_Hash.put("tMysqlInput_1", true);
				end_Hash.put("tMysqlInput_1", System.currentTimeMillis());

				/**
				 * [tMysqlInput_1 end ] stop
				 */

				/**
				 * [tBufferOutput_1 end ] start
				 */

				currentComponent = "tBufferOutput_1";

				ok_Hash.put("tBufferOutput_1", true);
				end_Hash.put("tBufferOutput_1", System.currentTimeMillis());

				/**
				 * [tBufferOutput_1 end ] stop
				 */

				/**
				 * [tMysqlRow_1 end ] start
				 */

				currentComponent = "tMysqlRow_1";

				stmt_tMysqlRow_1.close();

				ok_Hash.put("tMysqlRow_1", true);
				end_Hash.put("tMysqlRow_1", System.currentTimeMillis());

				/**
				 * [tMysqlRow_1 end ] stop
				 */

			}// end the resume

			if (resumeEntryMethodName == null || globalResumeTicket) {
				resumeUtil
						.addLog("CHECKPOINT",
								"CONNECTION:SUBJOB_OK:tMysqlInput_1:OnSubjobOk",
								"", Thread.currentThread().getId() + "", "",
								"", "", "", "");
			}

			tMysqlCommit_1Process(globalMap);

		} catch (java.lang.Exception e) {

			throw new TalendException(e, currentComponent, globalMap);

		} catch (java.lang.Error error) {

			throw error;

		}

		globalMap.put("tMysqlInput_1_SUBPROCESS_STATE", 1);
	}

	public void tMysqlCommit_1Process(
			final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tMysqlCommit_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";
		int iterateLoop = 0;
		String currentComponent = "";

		try {

			String currentMethodName = new java.lang.Exception()
					.getStackTrace()[0].getMethodName();
			boolean resumeIt = currentMethodName.equals(resumeEntryMethodName);
			if (resumeEntryMethodName == null || resumeIt || globalResumeTicket) {// start
																					// the
																					// resume
				globalResumeTicket = true;

				/**
				 * [tMysqlCommit_1 begin ] start
				 */

				ok_Hash.put("tMysqlCommit_1", false);
				start_Hash.put("tMysqlCommit_1", System.currentTimeMillis());
				currentComponent = "tMysqlCommit_1";

				int tos_count_tMysqlCommit_1 = 0;

				/**
				 * [tMysqlCommit_1 begin ] stop
				 */
				/**
				 * [tMysqlCommit_1 main ] start
				 */

				currentComponent = "tMysqlCommit_1";

				java.sql.Connection conn_tMysqlCommit_1 = (java.sql.Connection) globalMap
						.get("conn_tMysqlConnection_2");

				if (null == conn_tMysqlCommit_1) {
					java.util.Map<String, routines.system.TalendDataSource> dataSources_tMysqlCommit_1 = (java.util.Map<String, routines.system.TalendDataSource>) globalMap
							.get(KEY_DB_DATASOURCES);
					if (dataSources_tMysqlCommit_1 != null) {
						if (dataSources_tMysqlCommit_1.get("") != null) {
							conn_tMysqlCommit_1 = dataSources_tMysqlCommit_1
									.get("").getConnection();
						}
					}
				}

				if (conn_tMysqlCommit_1 != null
						&& !conn_tMysqlCommit_1.isClosed()) {
					conn_tMysqlCommit_1.commit();
					conn_tMysqlCommit_1.close();
				}

				tos_count_tMysqlCommit_1++;

				/**
				 * [tMysqlCommit_1 main ] stop
				 */
				/**
				 * [tMysqlCommit_1 end ] start
				 */

				currentComponent = "tMysqlCommit_1";

				ok_Hash.put("tMysqlCommit_1", true);
				end_Hash.put("tMysqlCommit_1", System.currentTimeMillis());

				/**
				 * [tMysqlCommit_1 end ] stop
				 */

			}// end the resume

			if (resumeEntryMethodName == null || globalResumeTicket) {
				resumeUtil
						.addLog("CHECKPOINT",
								"CONNECTION:SUBJOB_OK:tMysqlCommit_1:OnSubjobOk",
								"", Thread.currentThread().getId() + "", "",
								"", "", "", "");
			}

			tBufferInput_1Process(globalMap);

		} catch (java.lang.Exception e) {

			throw new TalendException(e, currentComponent, globalMap);

		} catch (java.lang.Error error) {

			throw error;

		}

		globalMap.put("tMysqlCommit_1_SUBPROCESS_STATE", 1);
	}

	public static class row4Struct implements
			routines.system.IPersistableRow<row4Struct> {
		final static byte[] commonByteArrayLock_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data = new byte[0];
		static byte[] commonByteArray_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data = new byte[0];

		public int jobid;

		public int getJobid() {
			return this.jobid;
		}

		public Integer profileid;

		public Integer getProfileid() {
			return this.profileid;
		}

		public Integer gaprofileid;

		public Integer getGaprofileid() {
			return this.gaprofileid;
		}

		private Integer readInteger(ObjectInputStream dis) throws IOException {
			Integer intReturn;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				intReturn = null;
			} else {
				intReturn = dis.readInt();
			}
			return intReturn;
		}

		private void writeInteger(Integer intNum, ObjectOutputStream dos)
				throws IOException {
			if (intNum == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeInt(intNum);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_ISLABS_MVMETRICS_ga_iterate_profile_2_poplate_initial_client_data) {

				try {

					int length = 0;

					this.jobid = dis.readInt();

					this.profileid = readInteger(dis);

					this.gaprofileid = readInteger(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// int

				dos.writeInt(this.jobid);

				// Integer

				writeInteger(this.profileid, dos);

				// Integer

				writeInteger(this.gaprofileid, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("jobid=" + String.valueOf(jobid));
			sb.append(",profileid=" + String.valueOf(profileid));
			sb.append(",gaprofileid=" + String.valueOf(gaprofileid));
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row4Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(),
						object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void tBufferInput_1Process(
			final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tBufferInput_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";
		int iterateLoop = 0;
		String currentComponent = "";

		try {

			String currentMethodName = new java.lang.Exception()
					.getStackTrace()[0].getMethodName();
			boolean resumeIt = currentMethodName.equals(resumeEntryMethodName);
			if (resumeEntryMethodName == null || resumeIt || globalResumeTicket) {// start
																					// the
																					// resume
				globalResumeTicket = true;

				row4Struct row4 = new row4Struct();

				/**
				 * [tFlowToIterate_1 begin ] start
				 */

				int NB_ITERATE_tRunJob_1 = 0; // for statistics

				ok_Hash.put("tFlowToIterate_1", false);
				start_Hash.put("tFlowToIterate_1", System.currentTimeMillis());
				currentComponent = "tFlowToIterate_1";

				int tos_count_tFlowToIterate_1 = 0;

				int nb_line_tFlowToIterate_1 = 0;
				int counter_tFlowToIterate_1 = 0;

				/**
				 * [tFlowToIterate_1 begin ] stop
				 */

				/**
				 * [tBufferInput_1 begin ] start
				 */

				ok_Hash.put("tBufferInput_1", false);
				start_Hash.put("tBufferInput_1", System.currentTimeMillis());
				currentComponent = "tBufferInput_1";

				int tos_count_tBufferInput_1 = 0;

				int nb_line_tBufferInput_1 = 0;

				String[] row_tBufferInput_1 = new String[3];
				for (int n = 0; n < globalBuffer.size(); n++) {
					row_tBufferInput_1 = (String[]) globalBuffer.get(n);
					if (0 < row_tBufferInput_1.length) {

						row4.jobid = ParserUtils
								.parseTo_int(row_tBufferInput_1[0]);

					}

					if (1 < row_tBufferInput_1.length) {

						row4.profileid = ParserUtils
								.parseTo_Integer(row_tBufferInput_1[1]);

					}

					if (2 < row_tBufferInput_1.length) {

						row4.gaprofileid = ParserUtils
								.parseTo_Integer(row_tBufferInput_1[2]);

					}

					/**
					 * [tBufferInput_1 begin ] stop
					 */
					/**
					 * [tBufferInput_1 main ] start
					 */

					currentComponent = "tBufferInput_1";

					tos_count_tBufferInput_1++;

					/**
					 * [tBufferInput_1 main ] stop
					 */

					/**
					 * [tFlowToIterate_1 main ] start
					 */

					currentComponent = "tFlowToIterate_1";

					globalMap.put("row4.jobid", row4.jobid);
					nb_line_tFlowToIterate_1++;
					globalMap.put("row4.profileid", row4.profileid);
					nb_line_tFlowToIterate_1++;
					globalMap.put("row4.gaprofileid", row4.gaprofileid);
					nb_line_tFlowToIterate_1++;

					counter_tFlowToIterate_1++;
					globalMap.put("tFlowToIterate_1_CURRENT_ITERATION",
							counter_tFlowToIterate_1);

					tos_count_tFlowToIterate_1++;

					/**
					 * [tFlowToIterate_1 main ] stop
					 */
					NB_ITERATE_tRunJob_1++;
					iterateLoop++;

					/**
					 * [tRunJob_1 begin ] start
					 */

					ok_Hash.put("tRunJob_1", false);
					start_Hash.put("tRunJob_1", System.currentTimeMillis());
					currentComponent = "tRunJob_1";

					int tos_count_tRunJob_1 = 0;

					/**
					 * [tRunJob_1 begin ] stop
					 */
					/**
					 * [tRunJob_1 main ] start
					 */

					currentComponent = "tRunJob_1";

					java.util.List<String> paraList_tRunJob_1 = new java.util.ArrayList<String>();
					paraList_tRunJob_1.add("--father_pid=" + pid);

					paraList_tRunJob_1.add("--root_pid=" + rootPid);

					paraList_tRunJob_1.add("--father_node=tRunJob_1");

					paraList_tRunJob_1.add("--context=Default");

					// for feature:10589
					paraList_tRunJob_1.add("--stat_port=" + portStats);

					if (resuming_logs_dir_path != null) {
						paraList_tRunJob_1.add("--resuming_logs_dir_path="
								+ resuming_logs_dir_path);
					}
					String childResumePath_tRunJob_1 = ResumeUtil
							.getChildJobCheckPointPath(resuming_checkpoint_path);
					String tRunJobName_tRunJob_1 = ResumeUtil
							.getRighttRunJob(resuming_checkpoint_path);
					if ("tRunJob_1".equals(tRunJobName_tRunJob_1)
							&& childResumePath_tRunJob_1 != null) {
						paraList_tRunJob_1
								.add("--resuming_checkpoint_path="
										+ ResumeUtil
												.getChildJobCheckPointPath(resuming_checkpoint_path));
					}
					paraList_tRunJob_1.add("--parent_part_launcher=JOB:"
							+ jobName + "/NODE:tRunJob_1");

					java.util.Map<String, Object> parentContextMap_tRunJob_1 = new java.util.HashMap<String, Object>();

					context.synchronizeContext();
					java.util.Enumeration<?> propertyNames_tRunJob_1 = context
							.propertyNames();
					while (propertyNames_tRunJob_1.hasMoreElements()) {
						String key_tRunJob_1 = (String) propertyNames_tRunJob_1
								.nextElement();
						Object value_tRunJob_1 = (Object) context
								.get(key_tRunJob_1);
						paraList_tRunJob_1.add("--context_param "
								+ key_tRunJob_1 + "=" + value_tRunJob_1);
					}

					parentContextMap_tRunJob_1.put("DB_HOST", context.DB_HOST);
					parentContextMap_tRunJob_1.put("DB_PORT", context.DB_PORT);
					parentContextMap_tRunJob_1.put("DB_SCHEMA",
							context.DB_SCHEMA);
					parentContextMap_tRunJob_1.put("DB_USERNAME",
							context.DB_USERNAME);
					parentContextMap_tRunJob_1.put("DB_PASSWORD",
							context.DB_PASSWORD);
					parentContextMap_tRunJob_1.put("DB_DBNAME",
							context.DB_DBNAME);
					parentContextMap_tRunJob_1.put("LOG_DIR_PATH",
							context.LOG_DIR_PATH);
					parentContextMap_tRunJob_1.put("CURRENT_DATE",
							context.CURRENT_DATE);
					parentContextMap_tRunJob_1.put("START_DATE",
							context.START_DATE);
					parentContextMap_tRunJob_1
							.put("END_DATE", context.END_DATE);
					parentContextMap_tRunJob_1.put("LAST_N_DAYS",
							context.LAST_N_DAYS);
					parentContextMap_tRunJob_1.put("SERVICE_ACCOUNT",
							context.SERVICE_ACCOUNT);
					parentContextMap_tRunJob_1
							.put("KEY_FILE", context.KEY_FILE);
					parentContextMap_tRunJob_1.put("PROFILE_ID",
							context.PROFILE_ID);
					parentContextMap_tRunJob_1.put("SMTP_PORT",
							context.SMTP_PORT);
					parentContextMap_tRunJob_1.put("SMTP_PASSWORD",
							context.SMTP_PASSWORD);
					parentContextMap_tRunJob_1.put("SMTP_USERNAME",
							context.SMTP_USERNAME);
					parentContextMap_tRunJob_1.put("SMTP_SERVER",
							context.SMTP_SERVER);
					parentContextMap_tRunJob_1.put("TEMP_DIR_PATH",
							context.TEMP_DIR_PATH);

					Object obj_tRunJob_1 = null;

					obj_tRunJob_1 = ((Integer) globalMap.get("row4.profileid"));
					paraList_tRunJob_1
							.add("--context_param PROFILE_ID="
									+ RuntimeUtils
											.tRunJobConvertContext(obj_tRunJob_1));
					parentContextMap_tRunJob_1.put("PROFILE_ID", obj_tRunJob_1);
					obj_tRunJob_1 = ((Integer) globalMap.get("row4.jobid"));
					paraList_tRunJob_1
							.add("--context_param JOB_ID="
									+ RuntimeUtils
											.tRunJobConvertContext(obj_tRunJob_1));
					parentContextMap_tRunJob_1.put("JOB_ID", obj_tRunJob_1);
					obj_tRunJob_1 = ((Integer) globalMap
							.get("row4.gaprofileid"));
					paraList_tRunJob_1
							.add("--context_param GAPROFILE="
									+ RuntimeUtils
											.tRunJobConvertContext(obj_tRunJob_1));
					parentContextMap_tRunJob_1.put("GAPROFILE", obj_tRunJob_1);
					islabs_mvmetrics.ga_populate_initial_client_data_0_1.ga_populate_initial_client_data childJob_tRunJob_1 = new islabs_mvmetrics.ga_populate_initial_client_data_0_1.ga_populate_initial_client_data();
					// pass DataSources
					java.util.Map<String, routines.system.TalendDataSource> talendDataSources_tRunJob_1 = (java.util.Map<String, routines.system.TalendDataSource>) globalMap
							.get(KEY_DB_DATASOURCES);
					if (null != talendDataSources_tRunJob_1) {
						java.util.Map<String, javax.sql.DataSource> dataSources_tRunJob_1 = new java.util.HashMap<String, javax.sql.DataSource>();
						for (java.util.Map.Entry<String, routines.system.TalendDataSource> talendDataSourceEntry_tRunJob_1 : talendDataSources_tRunJob_1
								.entrySet()) {
							dataSources_tRunJob_1.put(
									talendDataSourceEntry_tRunJob_1.getKey(),
									talendDataSourceEntry_tRunJob_1.getValue()
											.getRawDataSource());
						}
						childJob_tRunJob_1
								.setDataSources(dataSources_tRunJob_1);
					}
					childJob_tRunJob_1.parentContextMap = parentContextMap_tRunJob_1;
					String[][] childReturn_tRunJob_1 = childJob_tRunJob_1
							.runJob((String[]) paraList_tRunJob_1
									.toArray(new String[paraList_tRunJob_1
											.size()]));
					errorCode = childJob_tRunJob_1.getErrorCode();

					if (childJob_tRunJob_1.getErrorCode() == null) {
						globalMap.put(
								"tRunJob_1_CHILD_RETURN_CODE",
								childJob_tRunJob_1.getStatus() != null
										&& ("failure")
												.equals(childJob_tRunJob_1
														.getStatus()) ? 1 : 0);
					} else {
						globalMap.put("tRunJob_1_CHILD_RETURN_CODE",
								childJob_tRunJob_1.getErrorCode());
					}
					if (childJob_tRunJob_1.getExceptionStackTrace() != null) {
						globalMap.put("tRunJob_1_CHILD_EXCEPTION_STACKTRACE",
								childJob_tRunJob_1.getExceptionStackTrace());
					}

					tos_count_tRunJob_1++;

					/**
					 * [tRunJob_1 main ] stop
					 */
					/**
					 * [tRunJob_1 end ] start
					 */

					currentComponent = "tRunJob_1";

					ok_Hash.put("tRunJob_1", true);
					end_Hash.put("tRunJob_1", System.currentTimeMillis());

					/**
					 * [tRunJob_1 end ] stop
					 */

					/**
					 * [tBufferInput_1 end ] start
					 */

					currentComponent = "tBufferInput_1";

					nb_line_tBufferInput_1++;
				}
				globalMap.put("tBufferInput_1_NB_LINE", nb_line_tBufferInput_1);

				ok_Hash.put("tBufferInput_1", true);
				end_Hash.put("tBufferInput_1", System.currentTimeMillis());

				/**
				 * [tBufferInput_1 end ] stop
				 */

				/**
				 * [tFlowToIterate_1 end ] start
				 */

				currentComponent = "tFlowToIterate_1";

				globalMap.put("tFlowToIterate_1_NB_LINE",
						nb_line_tFlowToIterate_1);

				ok_Hash.put("tFlowToIterate_1", true);
				end_Hash.put("tFlowToIterate_1", System.currentTimeMillis());

				/**
				 * [tFlowToIterate_1 end ] stop
				 */

			}// end the resume

		} catch (java.lang.Exception e) {

			throw new TalendException(e, currentComponent, globalMap);

		} catch (java.lang.Error error) {

			throw error;

		}

		globalMap.put("tBufferInput_1_SUBPROCESS_STATE", 1);
	}

	public void tPrejob_1Process(final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tPrejob_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";
		int iterateLoop = 0;
		String currentComponent = "";

		try {

			String currentMethodName = new java.lang.Exception()
					.getStackTrace()[0].getMethodName();
			boolean resumeIt = currentMethodName.equals(resumeEntryMethodName);
			if (resumeEntryMethodName == null || resumeIt || globalResumeTicket) {// start
																					// the
																					// resume
				globalResumeTicket = true;

				/**
				 * [tPrejob_1 begin ] start
				 */

				ok_Hash.put("tPrejob_1", false);
				start_Hash.put("tPrejob_1", System.currentTimeMillis());
				currentComponent = "tPrejob_1";

				int tos_count_tPrejob_1 = 0;

				/**
				 * [tPrejob_1 begin ] stop
				 */
				/**
				 * [tPrejob_1 main ] start
				 */

				currentComponent = "tPrejob_1";

				tos_count_tPrejob_1++;

				/**
				 * [tPrejob_1 main ] stop
				 */
				/**
				 * [tPrejob_1 end ] start
				 */

				currentComponent = "tPrejob_1";

				ok_Hash.put("tPrejob_1", true);
				end_Hash.put("tPrejob_1", System.currentTimeMillis());

				tJava_1Process(globalMap);

				/**
				 * [tPrejob_1 end ] stop
				 */

			}// end the resume

		} catch (java.lang.Exception e) {

			throw new TalendException(e, currentComponent, globalMap);

		} catch (java.lang.Error error) {

			throw error;

		}

		globalMap.put("tPrejob_1_SUBPROCESS_STATE", 1);
	}

	public void tJava_1Process(final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tJava_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";
		int iterateLoop = 0;
		String currentComponent = "";

		try {

			String currentMethodName = new java.lang.Exception()
					.getStackTrace()[0].getMethodName();
			boolean resumeIt = currentMethodName.equals(resumeEntryMethodName);
			if (resumeEntryMethodName == null || resumeIt || globalResumeTicket) {// start
																					// the
																					// resume
				globalResumeTicket = true;

				/**
				 * [tJava_1 begin ] start
				 */

				ok_Hash.put("tJava_1", false);
				start_Hash.put("tJava_1", System.currentTimeMillis());
				currentComponent = "tJava_1";

				int tos_count_tJava_1 = 0;

				Date currentDate = TalendDate.getCurrentDate();
				String enddate = TalendDate.formatDate("yyyy-MM-dd",
						TalendDate.addDate(currentDate, -2, "dd"));
				String startdate = TalendDate.formatDate("yyyy-MM-dd",
						TalendDate.addDate(currentDate,
								0 - context.LAST_N_DAYS, "dd"));

				context.CURRENT_DATE = TalendDate.getDate("yyyyMMddHHmmss");
				context.START_DATE = startdate;
				context.END_DATE = enddate;

				/**
				 * [tJava_1 begin ] stop
				 */
				/**
				 * [tJava_1 main ] start
				 */

				currentComponent = "tJava_1";

				tos_count_tJava_1++;

				/**
				 * [tJava_1 main ] stop
				 */
				/**
				 * [tJava_1 end ] start
				 */

				currentComponent = "tJava_1";

				ok_Hash.put("tJava_1", true);
				end_Hash.put("tJava_1", System.currentTimeMillis());

				/**
				 * [tJava_1 end ] stop
				 */

			}// end the resume

		} catch (java.lang.Exception e) {

			throw new TalendException(e, currentComponent, globalMap);

		} catch (java.lang.Error error) {

			throw error;

		}

		globalMap.put("tJava_1_SUBPROCESS_STATE", 1);
	}

	public String resuming_logs_dir_path = null;
	public String resuming_checkpoint_path = null;
	public String parent_part_launcher = null;
	private String resumeEntryMethodName = null;
	private boolean globalResumeTicket = false;

	public boolean watch = false;
	// portStats is null, it means don't execute the statistics
	public Integer portStats = null;
	public int portTraces = 4334;
	public String clientHost;
	public String defaultClientHost = "localhost";
	public String contextStr = "Default";
	public boolean isDefaultContext = true;
	public String pid = "0";
	public String rootPid = null;
	public String fatherPid = null;
	public String fatherNode = null;
	public long startTime = 0;
	public boolean isChildJob = false;

	private boolean execStat = true;

	private ThreadLocal<java.util.Map<String, String>> threadLocal = new ThreadLocal<java.util.Map<String, String>>() {
		protected java.util.Map<String, String> initialValue() {
			java.util.Map<String, String> threadRunResultMap = new java.util.HashMap<String, String>();
			threadRunResultMap.put("errorCode", null);
			threadRunResultMap.put("status", "");
			return threadRunResultMap;
		};
	};

	private java.util.Properties context_param = new java.util.Properties();
	public java.util.Map<String, Object> parentContextMap = new java.util.HashMap<String, Object>();

	public String status = "";

	public static void main(String[] args) {
		final ga_iterate_profile_2_poplate_initial_client_data ga_iterate_profile_2_poplate_initial_client_dataClass = new ga_iterate_profile_2_poplate_initial_client_data();

		int exitCode = ga_iterate_profile_2_poplate_initial_client_dataClass
				.runJobInTOS(args);
		System.exit(exitCode);
	}

	public String[][] runJob(String[] args) {

		int exitCode = runJobInTOS(args);
		String[][] bufferValue = (String[][]) globalBuffer
				.toArray(new String[globalBuffer.size()][]);

		return bufferValue;
	}

	public int runJobInTOS(String[] args) {
		// reset status
		status = "";

		String lastStr = "";
		for (String arg : args) {
			if (arg.equalsIgnoreCase("--context_param")) {
				lastStr = arg;
			} else if (lastStr.equals("")) {
				evalParam(arg);
			} else {
				evalParam(lastStr + " " + arg);
				lastStr = "";
			}
		}

		if (clientHost == null) {
			clientHost = defaultClientHost;
		}

		if (pid == null || "0".equals(pid)) {
			pid = TalendString.getAsciiRandomString(6);
		}

		if (rootPid == null) {
			rootPid = pid;
		}
		if (fatherPid == null) {
			fatherPid = pid;
		} else {
			isChildJob = true;
		}

		try {
			// call job/subjob with an existing context, like:
			// --context=production. if without this parameter, there will use
			// the default context instead.
			java.io.InputStream inContext = ga_iterate_profile_2_poplate_initial_client_data.class
					.getClassLoader()
					.getResourceAsStream(
							"islabs_mvmetrics/ga_iterate_profile_2_poplate_initial_client_data_0_2/contexts/"
									+ contextStr + ".properties");
			if (isDefaultContext && inContext == null) {

			} else {
				if (inContext != null) {
					// defaultProps is in order to keep the original context
					// value
					defaultProps.load(inContext);
					inContext.close();
					context = new ContextProperties(defaultProps);
				} else {
					// print info and job continue to run, for case:
					// context_param is not empty.
					System.err.println("Could not find the context "
							+ contextStr);
				}
			}

			if (!context_param.isEmpty()) {
				context.putAll(context_param);
			}
			context.DB_HOST = (String) context.getProperty("DB_HOST");
			context.DB_PORT = (String) context.getProperty("DB_PORT");
			context.DB_SCHEMA = (String) context.getProperty("DB_SCHEMA");
			context.DB_USERNAME = (String) context.getProperty("DB_USERNAME");
			context.DB_PASSWORD = (String) context.getProperty("DB_PASSWORD");
			context.DB_DBNAME = (String) context.getProperty("DB_DBNAME");
			context.LOG_DIR_PATH = (String) context.getProperty("LOG_DIR_PATH");
			context.CURRENT_DATE = (String) context.getProperty("CURRENT_DATE");
			context.START_DATE = (String) context.getProperty("START_DATE");
			context.END_DATE = (String) context.getProperty("END_DATE");
			try {
				context.LAST_N_DAYS = routines.system.ParserUtils
						.parseTo_Integer(context.getProperty("LAST_N_DAYS"));
			} catch (NumberFormatException e) {
				context.LAST_N_DAYS = null;
			}
			context.SERVICE_ACCOUNT = (String) context
					.getProperty("SERVICE_ACCOUNT");
			context.KEY_FILE = (String) context.getProperty("KEY_FILE");
			try {
				context.PROFILE_ID = routines.system.ParserUtils
						.parseTo_Integer(context.getProperty("PROFILE_ID"));
			} catch (NumberFormatException e) {
				context.PROFILE_ID = null;
			}
			context.SMTP_PORT = (String) context.getProperty("SMTP_PORT");
			context.SMTP_PASSWORD = (String) context
					.getProperty("SMTP_PASSWORD");
			context.SMTP_USERNAME = (String) context
					.getProperty("SMTP_USERNAME");
			context.SMTP_SERVER = (String) context.getProperty("SMTP_SERVER");
			context.TEMP_DIR_PATH = (String) context
					.getProperty("TEMP_DIR_PATH");
		} catch (java.io.IOException ie) {
			System.err.println("Could not load context " + contextStr);
			ie.printStackTrace();
		}

		// get context value from parent directly
		if (parentContextMap != null && !parentContextMap.isEmpty()) {
			if (parentContextMap.containsKey("DB_HOST")) {
				context.DB_HOST = (String) parentContextMap.get("DB_HOST");
			}
			if (parentContextMap.containsKey("DB_PORT")) {
				context.DB_PORT = (String) parentContextMap.get("DB_PORT");
			}
			if (parentContextMap.containsKey("DB_SCHEMA")) {
				context.DB_SCHEMA = (String) parentContextMap.get("DB_SCHEMA");
			}
			if (parentContextMap.containsKey("DB_USERNAME")) {
				context.DB_USERNAME = (String) parentContextMap
						.get("DB_USERNAME");
			}
			if (parentContextMap.containsKey("DB_PASSWORD")) {
				context.DB_PASSWORD = (String) parentContextMap
						.get("DB_PASSWORD");
			}
			if (parentContextMap.containsKey("DB_DBNAME")) {
				context.DB_DBNAME = (String) parentContextMap.get("DB_DBNAME");
			}
			if (parentContextMap.containsKey("LOG_DIR_PATH")) {
				context.LOG_DIR_PATH = (String) parentContextMap
						.get("LOG_DIR_PATH");
			}
			if (parentContextMap.containsKey("CURRENT_DATE")) {
				context.CURRENT_DATE = (String) parentContextMap
						.get("CURRENT_DATE");
			}
			if (parentContextMap.containsKey("START_DATE")) {
				context.START_DATE = (String) parentContextMap
						.get("START_DATE");
			}
			if (parentContextMap.containsKey("END_DATE")) {
				context.END_DATE = (String) parentContextMap.get("END_DATE");
			}
			if (parentContextMap.containsKey("LAST_N_DAYS")) {
				context.LAST_N_DAYS = (Integer) parentContextMap
						.get("LAST_N_DAYS");
			}
			if (parentContextMap.containsKey("SERVICE_ACCOUNT")) {
				context.SERVICE_ACCOUNT = (String) parentContextMap
						.get("SERVICE_ACCOUNT");
			}
			if (parentContextMap.containsKey("KEY_FILE")) {
				context.KEY_FILE = (String) parentContextMap.get("KEY_FILE");
			}
			if (parentContextMap.containsKey("PROFILE_ID")) {
				context.PROFILE_ID = (Integer) parentContextMap
						.get("PROFILE_ID");
			}
			if (parentContextMap.containsKey("SMTP_PORT")) {
				context.SMTP_PORT = (String) parentContextMap.get("SMTP_PORT");
			}
			if (parentContextMap.containsKey("SMTP_PASSWORD")) {
				context.SMTP_PASSWORD = (String) parentContextMap
						.get("SMTP_PASSWORD");
			}
			if (parentContextMap.containsKey("SMTP_USERNAME")) {
				context.SMTP_USERNAME = (String) parentContextMap
						.get("SMTP_USERNAME");
			}
			if (parentContextMap.containsKey("SMTP_SERVER")) {
				context.SMTP_SERVER = (String) parentContextMap
						.get("SMTP_SERVER");
			}
			if (parentContextMap.containsKey("TEMP_DIR_PATH")) {
				context.TEMP_DIR_PATH = (String) parentContextMap
						.get("TEMP_DIR_PATH");
			}
		}

		// Resume: init the resumeUtil
		resumeEntryMethodName = ResumeUtil
				.getResumeEntryMethodName(resuming_checkpoint_path);
		resumeUtil = new ResumeUtil(resuming_logs_dir_path, isChildJob, rootPid);
		resumeUtil.initCommonInfo(pid, rootPid, fatherPid, projectName,
				jobName, contextStr, jobVersion);

		// Resume: jobStart
		resumeUtil.addLog("JOB_STARTED", "JOB:" + jobName,
				parent_part_launcher, Thread.currentThread().getId() + "", "",
				"", "", "", resumeUtil.convertToJsonText(context));

		java.util.concurrent.ConcurrentHashMap<Object, Object> concurrentHashMap = new java.util.concurrent.ConcurrentHashMap<Object, Object>();
		globalMap.put("concurrentHashMap", concurrentHashMap);

		long startUsedMemory = Runtime.getRuntime().totalMemory()
				- Runtime.getRuntime().freeMemory();
		long endUsedMemory = 0;
		long end = 0;

		startTime = System.currentTimeMillis();

		this.globalResumeTicket = true;// to run tPreJob

		try {
			errorCode = null;
			tPrejob_1Process(globalMap);
			if (!"failure".equals(status)) {
				status = "end";
			}
		} catch (TalendException e_tPrejob_1) {

			e_tPrejob_1.printStackTrace();
			globalMap.put("tPrejob_1_SUBPROCESS_STATE", -1);

		}

		this.globalResumeTicket = false;// to run others jobs

		try {
			errorCode = null;
			tMysqlConnection_2Process(globalMap);
			if (!"failure".equals(status)) {
				status = "end";
			}
		} catch (TalendException e_tMysqlConnection_2) {

			e_tMysqlConnection_2.printStackTrace();
			globalMap.put("tMysqlConnection_2_SUBPROCESS_STATE", -1);

		}

		this.globalResumeTicket = true;// to run tPostJob

		end = System.currentTimeMillis();

		if (watch) {
			System.out.println((end - startTime) + " milliseconds");
		}

		endUsedMemory = Runtime.getRuntime().totalMemory()
				- Runtime.getRuntime().freeMemory();
		if (false) {
			System.out
					.println((endUsedMemory - startUsedMemory)
							+ " bytes memory increase when running : ga_iterate_profile_2_poplate_initial_client_data");
		}

		int returnCode = 0;
		if (errorCode == null) {
			returnCode = status != null && status.equals("failure") ? 1 : 0;
		} else {
			returnCode = errorCode.intValue();
		}
		resumeUtil.addLog("JOB_ENDED", "JOB:" + jobName, parent_part_launcher,
				Thread.currentThread().getId() + "", "", "" + returnCode, "",
				"", "");

		return returnCode;

	}

	public void destroy() {

	}

	private java.util.Map<String, Object> getSharedConnections4REST() {
		java.util.Map<String, Object> connections = new java.util.HashMap<String, Object>();
		return connections;
	}

	private void evalParam(String arg) {
		if (arg.startsWith("--resuming_logs_dir_path")) {
			resuming_logs_dir_path = arg.substring(25);
		} else if (arg.startsWith("--resuming_checkpoint_path")) {
			resuming_checkpoint_path = arg.substring(27);
		} else if (arg.startsWith("--parent_part_launcher")) {
			parent_part_launcher = arg.substring(23);
		} else if (arg.startsWith("--watch")) {
			watch = true;
		} else if (arg.startsWith("--stat_port=")) {
			String portStatsStr = arg.substring(12);
			if (portStatsStr != null && !portStatsStr.equals("null")) {
				portStats = Integer.parseInt(portStatsStr);
			}
		} else if (arg.startsWith("--trace_port=")) {
			portTraces = Integer.parseInt(arg.substring(13));
		} else if (arg.startsWith("--client_host=")) {
			clientHost = arg.substring(14);
		} else if (arg.startsWith("--context=")) {
			contextStr = arg.substring(10);
			isDefaultContext = false;
		} else if (arg.startsWith("--father_pid=")) {
			fatherPid = arg.substring(13);
		} else if (arg.startsWith("--root_pid=")) {
			rootPid = arg.substring(11);
		} else if (arg.startsWith("--father_node=")) {
			fatherNode = arg.substring(14);
		} else if (arg.startsWith("--pid=")) {
			pid = arg.substring(6);
		} else if (arg.startsWith("--context_param")) {
			String keyValue = arg.substring(16);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.put(keyValue.substring(0, index),
							replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.put(keyValue.substring(0, index),
							keyValue.substring(index + 1));
				}
			}
		}

	}

	private final String[][] escapeChars = { { "\\n", "\n" }, { "\\'", "\'" },
			{ "\\r", "\r" }, { "\\f", "\f" }, { "\\b", "\b" }, { "\\t", "\t" },
			{ "\\\\", "\\" } };

	private String replaceEscapeChars(String keyValue) {
		if (keyValue == null || ("").equals(keyValue.trim())) {
			return keyValue;
		}
		for (String[] strArray : escapeChars) {
			keyValue = keyValue.replace(strArray[0], strArray[1]);
		}
		return keyValue;
	}

	public Integer getErrorCode() {
		return errorCode;
	}

	public String getStatus() {
		return status;
	}

	ResumeUtil resumeUtil = null;
}
/************************************************************************************************
 * 93274 characters generated by Talend Open Studio for Data Integration on the
 * 12 August 2013 13:39:39 IST
 ************************************************************************************************/
