// ============================================================================
//
// Copyright (c) 2006-2013, Talend Inc.
//
// This source code has been automatically generated by_Talend Open Studio for Data Integration
// / Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package islabs_mvmetrics.dymanically_fetching_ga_data_0_1;

import routines.Mathematical;
import routines.DataOperation;
import routines.Relational;
import routines.TalendDate;
import routines.TalendDataGenerator;
import routines.Numeric;
import routines.islabs_ga_common;
import routines.TalendString;
import routines.StringHandling;
import routines.system.*;
import routines.system.api.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.util.Comparator;

//the import part of tJava_1
//import java.util.List;

@SuppressWarnings("unused")
/**
 * Job: Dymanically_Fetching_GA_Data Purpose: <br>
 * Description:  <br>
 * @author test@talend.com
 * @version 5.3.1.r104014
 * @status 
 */
public class Dymanically_Fetching_GA_Data implements TalendJob {

	public final Object obj = new Object();

	// for transmiting parameters purpose
	private Object valueObject = null;

	public Object getValueObject() {
		return this.valueObject;
	}

	public void setValueObject(Object valueObject) {
		this.valueObject = valueObject;
	}

	private final static String defaultCharset = java.nio.charset.Charset
			.defaultCharset().name();

	private final static String utf8Charset = "UTF-8";

	// create and load default properties
	private java.util.Properties defaultProps = new java.util.Properties();

	// create application properties with default
	public class ContextProperties extends java.util.Properties {

		private static final long serialVersionUID = 1L;

		public ContextProperties(java.util.Properties properties) {
			super(properties);
		}

		public ContextProperties() {
			super();
		}

		public void synchronizeContext() {

			if (END_DATE != null) {

				this.setProperty("END_DATE", END_DATE.toString());

			}

			if (START_DATE != null) {

				this.setProperty("START_DATE", START_DATE.toString());

			}

			if (CONN_HOST != null) {

				this.setProperty("CONN_HOST", CONN_HOST.toString());

			}

			if (PORT != null) {

				this.setProperty("PORT", PORT.toString());

			}

			if (DATABASE != null) {

				this.setProperty("DATABASE", DATABASE.toString());

			}

			if (USER_NAME != null) {

				this.setProperty("USER_NAME", USER_NAME.toString());

			}

			if (PASSWORD != null) {

				this.setProperty("PASSWORD", PASSWORD.toString());

			}

			if (SERVICE_ACCOUNT != null) {

				this.setProperty("SERVICE_ACCOUNT", SERVICE_ACCOUNT.toString());

			}

			if (KEY_FILE != null) {

				this.setProperty("KEY_FILE", KEY_FILE.toString());

			}

			if (PROFILE_ID != null) {

				this.setProperty("PROFILE_ID", PROFILE_ID.toString());

			}

			if (GAPROFILE_ID != null) {

				this.setProperty("GAPROFILE_ID", GAPROFILE_ID.toString());

			}

			if (LOG_FILE_DIR != null) {

				this.setProperty("LOG_FILE_DIR", LOG_FILE_DIR.toString());

			}

			if (CURRENT_DATE != null) {

				this.setProperty("CURRENT_DATE", CURRENT_DATE.toString());

			}

			if (DynamicFetch_AdditionalParams != null) {

				this.setProperty("DynamicFetch_AdditionalParams",
						DynamicFetch_AdditionalParams.toString());

			}

			if (DynamicFetch_Login != null) {

				this.setProperty("DynamicFetch_Login",
						DynamicFetch_Login.toString());

			}

			if (DynamicFetch_Database != null) {

				this.setProperty("DynamicFetch_Database",
						DynamicFetch_Database.toString());

			}

			if (DynamicFetch_Password != null) {

				this.setProperty("DynamicFetch_Password",
						DynamicFetch_Password.toString());

			}

			if (DynamicFetch_Server != null) {

				this.setProperty("DynamicFetch_Server",
						DynamicFetch_Server.toString());

			}

			if (DynamicFetch_Port != null) {

				this.setProperty("DynamicFetch_Port",
						DynamicFetch_Port.toString());

			}

		}

		public String END_DATE;

		public String getEND_DATE() {
			return this.END_DATE;
		}

		public String START_DATE;

		public String getSTART_DATE() {
			return this.START_DATE;
		}

		public String CONN_HOST;

		public String getCONN_HOST() {
			return this.CONN_HOST;
		}

		public String PORT;

		public String getPORT() {
			return this.PORT;
		}

		public String DATABASE;

		public String getDATABASE() {
			return this.DATABASE;
		}

		public String USER_NAME;

		public String getUSER_NAME() {
			return this.USER_NAME;
		}

		public String PASSWORD;

		public String getPASSWORD() {
			return this.PASSWORD;
		}

		public String SERVICE_ACCOUNT;

		public String getSERVICE_ACCOUNT() {
			return this.SERVICE_ACCOUNT;
		}

		public String KEY_FILE;

		public String getKEY_FILE() {
			return this.KEY_FILE;
		}

		public String PROFILE_ID;

		public String getPROFILE_ID() {
			return this.PROFILE_ID;
		}

		public String GAPROFILE_ID;

		public String getGAPROFILE_ID() {
			return this.GAPROFILE_ID;
		}

		public String LOG_FILE_DIR;

		public String getLOG_FILE_DIR() {
			return this.LOG_FILE_DIR;
		}

		public String CURRENT_DATE;

		public String getCURRENT_DATE() {
			return this.CURRENT_DATE;
		}

		public String DynamicFetch_AdditionalParams;

		public String getDynamicFetch_AdditionalParams() {
			return this.DynamicFetch_AdditionalParams;
		}

		public String DynamicFetch_Login;

		public String getDynamicFetch_Login() {
			return this.DynamicFetch_Login;
		}

		public String DynamicFetch_Database;

		public String getDynamicFetch_Database() {
			return this.DynamicFetch_Database;
		}

		public java.lang.String DynamicFetch_Password;

		public java.lang.String getDynamicFetch_Password() {
			return this.DynamicFetch_Password;
		}

		public String DynamicFetch_Server;

		public String getDynamicFetch_Server() {
			return this.DynamicFetch_Server;
		}

		public String DynamicFetch_Port;

		public String getDynamicFetch_Port() {
			return this.DynamicFetch_Port;
		}
	}

	private ContextProperties context = new ContextProperties();

	public ContextProperties getContext() {
		return this.context;
	}

	private final String jobVersion = "0.1";
	private final String jobName = "Dymanically_Fetching_GA_Data";
	private final String projectName = "ISLABS_MVMETRICS";
	public Integer errorCode = null;
	private String currentComponent = "";
	private final java.util.Map<String, Long> start_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Long> end_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Boolean> ok_Hash = new java.util.HashMap<String, Boolean>();
	private final java.util.Map<String, Object> globalMap = new java.util.HashMap<String, Object>();
	public final java.util.List<String[]> globalBuffer = new java.util.ArrayList<String[]>();

	public boolean isExportedAsOSGI = false;

	// OSGi DataSource
	private final static String KEY_DB_DATASOURCES = "KEY_DB_DATASOURCES";

	public void setDataSources(
			java.util.Map<String, javax.sql.DataSource> dataSources) {
		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		for (java.util.Map.Entry<String, javax.sql.DataSource> dataSourceEntry : dataSources
				.entrySet()) {
			talendDataSources.put(
					dataSourceEntry.getKey(),
					new routines.system.TalendDataSource(dataSourceEntry
							.getValue()));
		}
		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
	}

	LogCatcherUtils tLogCatcher_1 = new LogCatcherUtils();

	private final java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
	private final java.io.PrintStream errorMessagePS = new java.io.PrintStream(
			new java.io.BufferedOutputStream(baos));

	public String getExceptionStackTrace() {
		if ("failure".equals(this.getStatus())) {
			errorMessagePS.flush();
			return baos.toString();
		}
		return null;
	}

	private java.lang.Exception exception = null;

	public java.lang.Exception getException() {
		if ("failure".equals(this.getStatus())) {
			return this.exception;
		}
		return null;
	}

	private class TalendException extends java.lang.Exception {

		private static final long serialVersionUID = 1L;

		private java.util.Map<String, Object> globalMap = null;
		private java.lang.Exception e = null;
		private String currentComponent = null;

		private TalendException(java.lang.Exception e, String errorComponent,
				final java.util.Map<String, Object> globalMap) {
			this.currentComponent = errorComponent;
			this.globalMap = globalMap;
			this.e = e;
		}

		public java.lang.Exception getException() {
			return this.e;
		}

		public String getCurrentComponent() {
			return this.currentComponent;
		}

		@Override
		public void printStackTrace() {
			if (!(e instanceof TalendException || e instanceof TDieException)) {
				globalMap.put(currentComponent + "_ERROR_MESSAGE",
						e.getMessage());
				System.err
						.println("Exception in component " + currentComponent);
			}
			if (!(e instanceof TDieException)) {
				if (e instanceof TalendException) {
					e.printStackTrace();
				} else {
					e.printStackTrace();
					e.printStackTrace(errorMessagePS);
					Dymanically_Fetching_GA_Data.this.exception = e;
				}
			}
			if (!(e instanceof TalendException)) {
				try {
					for (java.lang.reflect.Method m : this.getClass()
							.getEnclosingClass().getMethods()) {
						if (m.getName().compareTo(currentComponent + "_error") == 0) {
							m.invoke(Dymanically_Fetching_GA_Data.this,
									new Object[] { e, currentComponent,
											globalMap });
							break;
						}
					}

					if (!(e instanceof TDieException)) {
						tLogCatcher_1.addMessage("Java Exception",
								currentComponent, 6, e.getClass().getName()
										+ ":" + e.getMessage(), 1);
						tLogCatcher_1Process(globalMap);
					}
				} catch (java.lang.SecurityException e) {
					this.e.printStackTrace();
				} catch (java.lang.IllegalArgumentException e) {
					this.e.printStackTrace();
				} catch (java.lang.IllegalAccessException e) {
					this.e.printStackTrace();
				} catch (java.lang.reflect.InvocationTargetException e) {
					this.e.printStackTrace();
				} catch (TalendException e) {
					// do nothing
				}

			}
		}
	}

	public void tJava_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tJava_1", System.currentTimeMillis());

		status = "failure";

		tJava_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tMysqlConnection_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tMysqlConnection_1", System.currentTimeMillis());

		status = "failure";

		tMysqlConnection_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tGoogleAnalyticsInput_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tGoogleAnalyticsInput_1", System.currentTimeMillis());

		status = "failure";

		tGoogleAnalyticsInput_1_onSubJobError(exception, errorComponent,
				globalMap);
	}

	public void tMap_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tMap_1", System.currentTimeMillis());

		status = "failure";

		tGoogleAnalyticsInput_1_onSubJobError(exception, errorComponent,
				globalMap);
	}

	public void tMysqlOutput_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tMysqlOutput_1", System.currentTimeMillis());

		status = "failure";

		tGoogleAnalyticsInput_1_onSubJobError(exception, errorComponent,
				globalMap);
	}

	public void tMysqlCommit_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tMysqlCommit_1", System.currentTimeMillis());

		status = "failure";

		tMysqlCommit_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tLogCatcher_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tLogCatcher_1", System.currentTimeMillis());

		status = "failure";

		tLogCatcher_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tMap_2_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tMap_2", System.currentTimeMillis());

		status = "failure";

		tLogCatcher_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tFileOutputDelimited_1_error(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {
		end_Hash.put("tFileOutputDelimited_1", System.currentTimeMillis());

		status = "failure";

		tLogCatcher_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tJava_1_onSubJobError(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tMysqlConnection_1_onSubJobError(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tGoogleAnalyticsInput_1_onSubJobError(
			java.lang.Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tMysqlCommit_1_onSubJobError(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tLogCatcher_1_onSubJobError(java.lang.Exception exception,
			String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread
				.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(),
				ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tJava_1Process(final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tJava_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";
		int iterateLoop = 0;
		String currentComponent = "";

		try {

			String currentMethodName = new java.lang.Exception()
					.getStackTrace()[0].getMethodName();
			boolean resumeIt = currentMethodName.equals(resumeEntryMethodName);
			if (resumeEntryMethodName == null || resumeIt || globalResumeTicket) {// start
																					// the
																					// resume
				globalResumeTicket = true;

				/**
				 * [tJava_1 begin ] start
				 */

				ok_Hash.put("tJava_1", false);
				start_Hash.put("tJava_1", System.currentTimeMillis());
				currentComponent = "tJava_1";

				int tos_count_tJava_1 = 0;

				System.out.println("Populating Data for GA Profile : "
						+ context.GAPROFILE_ID);
				// System.out.println(TalendDate.formatDate("yyyy-MM-dd",
				// TalendDate.addDate(TalendDate.getCurrentDate(),-1,"DD")));

				context.START_DATE = TalendDate.formatDate("yyyy-MM-dd",
						TalendDate.addDate(TalendDate.getCurrentDate(), -1,
								"DD"));

				/**
				 * [tJava_1 begin ] stop
				 */
				/**
				 * [tJava_1 main ] start
				 */

				currentComponent = "tJava_1";

				tos_count_tJava_1++;

				/**
				 * [tJava_1 main ] stop
				 */
				/**
				 * [tJava_1 end ] start
				 */

				currentComponent = "tJava_1";

				ok_Hash.put("tJava_1", true);
				end_Hash.put("tJava_1", System.currentTimeMillis());

				tMysqlConnection_1Process(globalMap);

				/**
				 * [tJava_1 end ] stop
				 */

			}// end the resume

		} catch (java.lang.Exception e) {

			throw new TalendException(e, currentComponent, globalMap);

		} catch (java.lang.Error error) {

			throw error;

		}

		globalMap.put("tJava_1_SUBPROCESS_STATE", 1);
	}

	public void tMysqlConnection_1Process(
			final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tMysqlConnection_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";
		int iterateLoop = 0;
		String currentComponent = "";

		try {

			String currentMethodName = new java.lang.Exception()
					.getStackTrace()[0].getMethodName();
			boolean resumeIt = currentMethodName.equals(resumeEntryMethodName);
			if (resumeEntryMethodName == null || resumeIt || globalResumeTicket) {// start
																					// the
																					// resume
				globalResumeTicket = true;

				/**
				 * [tMysqlConnection_1 begin ] start
				 */

				ok_Hash.put("tMysqlConnection_1", false);
				start_Hash
						.put("tMysqlConnection_1", System.currentTimeMillis());
				currentComponent = "tMysqlConnection_1";

				int tos_count_tMysqlConnection_1 = 0;

				String properties_tMysqlConnection_1 = "noDatetimeStringSync=true";
				if (properties_tMysqlConnection_1 == null
						|| properties_tMysqlConnection_1.trim().length() == 0) {
					properties_tMysqlConnection_1 += "rewriteBatchedStatements=true";
				} else if (properties_tMysqlConnection_1 != null
						&& !properties_tMysqlConnection_1
								.contains("rewriteBatchedStatements")) {
					properties_tMysqlConnection_1 += "&rewriteBatchedStatements=true";
				}

				String url_tMysqlConnection_1 = "jdbc:mysql://"
						+ context.CONN_HOST + ":" + context.PORT + "/"
						+ context.DATABASE + "?"
						+ properties_tMysqlConnection_1;

				String userName_tMysqlConnection_1 = context.USER_NAME;
				String password_tMysqlConnection_1 = context.PASSWORD;

				java.sql.Connection conn_tMysqlConnection_1 = null;

				if ((null == globalMap.get(KEY_DB_DATASOURCES))
						|| "".equals("")) {

					java.lang.Class.forName("org.gjt.mm.mysql.Driver");

					conn_tMysqlConnection_1 = java.sql.DriverManager
							.getConnection(url_tMysqlConnection_1,
									userName_tMysqlConnection_1,
									password_tMysqlConnection_1);
					globalMap.put("conn_tMysqlConnection_1",
							conn_tMysqlConnection_1);
				}
				if (null != conn_tMysqlConnection_1) {

					conn_tMysqlConnection_1.setAutoCommit(false);
				}

				globalMap.put("conn_tMysqlConnection_1",
						conn_tMysqlConnection_1);

				globalMap.put("db_tMysqlConnection_1", context.DATABASE);

				/**
				 * [tMysqlConnection_1 begin ] stop
				 */
				/**
				 * [tMysqlConnection_1 main ] start
				 */

				currentComponent = "tMysqlConnection_1";

				tos_count_tMysqlConnection_1++;

				/**
				 * [tMysqlConnection_1 main ] stop
				 */
				/**
				 * [tMysqlConnection_1 end ] start
				 */

				currentComponent = "tMysqlConnection_1";

				ok_Hash.put("tMysqlConnection_1", true);
				end_Hash.put("tMysqlConnection_1", System.currentTimeMillis());

				/**
				 * [tMysqlConnection_1 end ] stop
				 */

			}// end the resume

			if (resumeEntryMethodName == null || globalResumeTicket) {
				resumeUtil.addLog("CHECKPOINT",
						"CONNECTION:SUBJOB_OK:tMysqlConnection_1:OnSubjobOk",
						"", Thread.currentThread().getId() + "", "", "", "",
						"", "");
			}

			tGoogleAnalyticsInput_1Process(globalMap);

		} catch (java.lang.Exception e) {

			throw new TalendException(e, currentComponent, globalMap);

		} catch (java.lang.Error error) {

			throw error;

		}

		globalMap.put("tMysqlConnection_1_SUBPROCESS_STATE", 1);
	}

	public static class AnalyticsStruct implements
			routines.system.IPersistableRow<AnalyticsStruct> {
		final static byte[] commonByteArrayLock_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[0];
		static byte[] commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[0];
		protected static final int DEFAULT_HASHCODE = 1;
		protected static final int PRIME = 31;
		protected int hashCode = DEFAULT_HASHCODE;
		public boolean hashCodeDirty = true;

		public String loopKey;

		public int profileid;

		public int getProfileid() {
			return this.profileid;
		}

		public java.util.Date date;

		public java.util.Date getDate() {
			return this.date;
		}

		public Integer visits;

		public Integer getVisits() {
			return this.visits;
		}

		public Integer visitors;

		public Integer getVisitors() {
			return this.visitors;
		}

		public String visitorType;

		public String getVisitorType() {
			return this.visitorType;
		}

		public String isMobile;

		public String getIsMobile() {
			return this.isMobile;
		}

		public String medium;

		public String getMedium() {
			return this.medium;
		}

		public String medium_1;

		public String getMedium_1() {
			return this.medium_1;
		}

		public String source;

		public String getSource() {
			return this.source;
		}

		public Integer goalCompletionsAll;

		public Integer getGoalCompletionsAll() {
			return this.goalCompletionsAll;
		}

		public Float goalConversionRateAll;

		public Float getGoalConversionRateAll() {
			return this.goalConversionRateAll;
		}

		public Float visitBounceRate;

		public Float getVisitBounceRate() {
			return this.visitBounceRate;
		}

		public Integer avgTimeOnSite;

		public Integer getAvgTimeOnSite() {
			return this.avgTimeOnSite;
		}

		public Integer pageviewsPerVisit;

		public Integer getPageviewsPerVisit() {
			return this.pageviewsPerVisit;
		}

		@Override
		public int hashCode() {
			if (this.hashCodeDirty) {
				final int prime = PRIME;
				int result = DEFAULT_HASHCODE;

				result = prime * result + (int) this.profileid;

				result = prime * result
						+ ((this.date == null) ? 0 : this.date.hashCode());

				this.hashCode = result;
				this.hashCodeDirty = false;
			}
			return this.hashCode;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			final AnalyticsStruct other = (AnalyticsStruct) obj;

			if (this.profileid != other.profileid)
				return false;

			if (this.date == null) {
				if (other.date != null)
					return false;
			} else if (!this.date.equals(other.date))
				return false;

			return true;
		}

		public void copyDataTo(AnalyticsStruct other) {

			other.profileid = this.profileid;
			other.date = this.date;
			other.visits = this.visits;
			other.visitors = this.visitors;
			other.visitorType = this.visitorType;
			other.isMobile = this.isMobile;
			other.medium = this.medium;
			other.medium_1 = this.medium_1;
			other.source = this.source;
			other.goalCompletionsAll = this.goalCompletionsAll;
			other.goalConversionRateAll = this.goalConversionRateAll;
			other.visitBounceRate = this.visitBounceRate;
			other.avgTimeOnSite = this.avgTimeOnSite;
			other.pageviewsPerVisit = this.pageviewsPerVisit;

		}

		public void copyKeysDataTo(AnalyticsStruct other) {

			other.profileid = this.profileid;
			other.date = this.date;

		}

		private java.util.Date readDate(ObjectInputStream dis)
				throws IOException {
			java.util.Date dateReturn = null;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				dateReturn = null;
			} else {
				dateReturn = new Date(dis.readLong());
			}
			return dateReturn;
		}

		private void writeDate(java.util.Date date1, ObjectOutputStream dos)
				throws IOException {
			if (date1 == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeLong(date1.getTime());
			}
		}

		private Integer readInteger(ObjectInputStream dis) throws IOException {
			Integer intReturn;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				intReturn = null;
			} else {
				intReturn = dis.readInt();
			}
			return intReturn;
		}

		private void writeInteger(Integer intNum, ObjectOutputStream dos)
				throws IOException {
			if (intNum == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeInt(intNum);
			}
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data.length) {
					if (length < 1024
							&& commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data.length == 0) {
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[1024];
					} else {
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[2 * length];
					}
				}
				dis.readFully(
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data,
						0, length);
				strReturn = new String(
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data,
						0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos)
				throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data) {

				try {

					int length = 0;

					this.profileid = dis.readInt();

					this.date = readDate(dis);

					this.visits = readInteger(dis);

					this.visitors = readInteger(dis);

					this.visitorType = readString(dis);

					this.isMobile = readString(dis);

					this.medium = readString(dis);

					this.medium_1 = readString(dis);

					this.source = readString(dis);

					this.goalCompletionsAll = readInteger(dis);

					length = dis.readByte();
					if (length == -1) {
						this.goalConversionRateAll = null;
					} else {
						this.goalConversionRateAll = dis.readFloat();
					}

					length = dis.readByte();
					if (length == -1) {
						this.visitBounceRate = null;
					} else {
						this.visitBounceRate = dis.readFloat();
					}

					this.avgTimeOnSite = readInteger(dis);

					this.pageviewsPerVisit = readInteger(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// int

				dos.writeInt(this.profileid);

				// java.util.Date

				writeDate(this.date, dos);

				// Integer

				writeInteger(this.visits, dos);

				// Integer

				writeInteger(this.visitors, dos);

				// String

				writeString(this.visitorType, dos);

				// String

				writeString(this.isMobile, dos);

				// String

				writeString(this.medium, dos);

				// String

				writeString(this.medium_1, dos);

				// String

				writeString(this.source, dos);

				// Integer

				writeInteger(this.goalCompletionsAll, dos);

				// Float

				if (this.goalConversionRateAll == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeFloat(this.goalConversionRateAll);
				}

				// Float

				if (this.visitBounceRate == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeFloat(this.visitBounceRate);
				}

				// Integer

				writeInteger(this.avgTimeOnSite, dos);

				// Integer

				writeInteger(this.pageviewsPerVisit, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("profileid=" + String.valueOf(profileid));
			sb.append(",date=" + String.valueOf(date));
			sb.append(",visits=" + String.valueOf(visits));
			sb.append(",visitors=" + String.valueOf(visitors));
			sb.append(",visitorType=" + visitorType);
			sb.append(",isMobile=" + isMobile);
			sb.append(",medium=" + medium);
			sb.append(",medium_1=" + medium_1);
			sb.append(",source=" + source);
			sb.append(",goalCompletionsAll="
					+ String.valueOf(goalCompletionsAll));
			sb.append(",goalConversionRateAll="
					+ String.valueOf(goalConversionRateAll));
			sb.append(",visitBounceRate=" + String.valueOf(visitBounceRate));
			sb.append(",avgTimeOnSite=" + String.valueOf(avgTimeOnSite));
			sb.append(",pageviewsPerVisit=" + String.valueOf(pageviewsPerVisit));
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(AnalyticsStruct other) {

			int returnValue = -1;

			returnValue = checkNullsAndCompare(this.profileid, other.profileid);
			if (returnValue != 0) {
				return returnValue;
			}

			returnValue = checkNullsAndCompare(this.date, other.date);
			if (returnValue != 0) {
				return returnValue;
			}

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(),
						object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public static class row2Struct implements
			routines.system.IPersistableRow<row2Struct> {
		final static byte[] commonByteArrayLock_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[0];
		static byte[] commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[0];

		public String visitorType;

		public String getVisitorType() {
			return this.visitorType;
		}

		public String isMobile;

		public String getIsMobile() {
			return this.isMobile;
		}

		public String medium;

		public String getMedium() {
			return this.medium;
		}

		public String source;

		public String getSource() {
			return this.source;
		}

		public String date;

		public String getDate() {
			return this.date;
		}

		public Integer visits;

		public Integer getVisits() {
			return this.visits;
		}

		public Integer visitors;

		public Integer getVisitors() {
			return this.visitors;
		}

		public Integer goalCompletionsAll;

		public Integer getGoalCompletionsAll() {
			return this.goalCompletionsAll;
		}

		public Float goalConversionRateAll;

		public Float getGoalConversionRateAll() {
			return this.goalConversionRateAll;
		}

		public Float visitBounceRate;

		public Float getVisitBounceRate() {
			return this.visitBounceRate;
		}

		public Integer avgTimeOnSite;

		public Integer getAvgTimeOnSite() {
			return this.avgTimeOnSite;
		}

		public Integer pageviewsPerVisit;

		public Integer getPageviewsPerVisit() {
			return this.pageviewsPerVisit;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data.length) {
					if (length < 1024
							&& commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data.length == 0) {
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[1024];
					} else {
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[2 * length];
					}
				}
				dis.readFully(
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data,
						0, length);
				strReturn = new String(
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data,
						0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos)
				throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		private Integer readInteger(ObjectInputStream dis) throws IOException {
			Integer intReturn;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				intReturn = null;
			} else {
				intReturn = dis.readInt();
			}
			return intReturn;
		}

		private void writeInteger(Integer intNum, ObjectOutputStream dos)
				throws IOException {
			if (intNum == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeInt(intNum);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data) {

				try {

					int length = 0;

					this.visitorType = readString(dis);

					this.isMobile = readString(dis);

					this.medium = readString(dis);

					this.source = readString(dis);

					this.date = readString(dis);

					this.visits = readInteger(dis);

					this.visitors = readInteger(dis);

					this.goalCompletionsAll = readInteger(dis);

					length = dis.readByte();
					if (length == -1) {
						this.goalConversionRateAll = null;
					} else {
						this.goalConversionRateAll = dis.readFloat();
					}

					length = dis.readByte();
					if (length == -1) {
						this.visitBounceRate = null;
					} else {
						this.visitBounceRate = dis.readFloat();
					}

					this.avgTimeOnSite = readInteger(dis);

					this.pageviewsPerVisit = readInteger(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// String

				writeString(this.visitorType, dos);

				// String

				writeString(this.isMobile, dos);

				// String

				writeString(this.medium, dos);

				// String

				writeString(this.source, dos);

				// String

				writeString(this.date, dos);

				// Integer

				writeInteger(this.visits, dos);

				// Integer

				writeInteger(this.visitors, dos);

				// Integer

				writeInteger(this.goalCompletionsAll, dos);

				// Float

				if (this.goalConversionRateAll == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeFloat(this.goalConversionRateAll);
				}

				// Float

				if (this.visitBounceRate == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeFloat(this.visitBounceRate);
				}

				// Integer

				writeInteger(this.avgTimeOnSite, dos);

				// Integer

				writeInteger(this.pageviewsPerVisit, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("visitorType=" + visitorType);
			sb.append(",isMobile=" + isMobile);
			sb.append(",medium=" + medium);
			sb.append(",source=" + source);
			sb.append(",date=" + date);
			sb.append(",visits=" + String.valueOf(visits));
			sb.append(",visitors=" + String.valueOf(visitors));
			sb.append(",goalCompletionsAll="
					+ String.valueOf(goalCompletionsAll));
			sb.append(",goalConversionRateAll="
					+ String.valueOf(goalConversionRateAll));
			sb.append(",visitBounceRate=" + String.valueOf(visitBounceRate));
			sb.append(",avgTimeOnSite=" + String.valueOf(avgTimeOnSite));
			sb.append(",pageviewsPerVisit=" + String.valueOf(pageviewsPerVisit));
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row2Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(),
						object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void tGoogleAnalyticsInput_1Process(
			final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tGoogleAnalyticsInput_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";
		int iterateLoop = 0;
		String currentComponent = "";

		try {

			String currentMethodName = new java.lang.Exception()
					.getStackTrace()[0].getMethodName();
			boolean resumeIt = currentMethodName.equals(resumeEntryMethodName);
			if (resumeEntryMethodName == null || resumeIt || globalResumeTicket) {// start
																					// the
																					// resume
				globalResumeTicket = true;

				row2Struct row2 = new row2Struct();
				AnalyticsStruct Analytics = new AnalyticsStruct();

				/**
				 * [tMysqlOutput_1 begin ] start
				 */

				ok_Hash.put("tMysqlOutput_1", false);
				start_Hash.put("tMysqlOutput_1", System.currentTimeMillis());
				currentComponent = "tMysqlOutput_1";

				int tos_count_tMysqlOutput_1 = 0;

				int nb_line_tMysqlOutput_1 = 0;
				int nb_line_update_tMysqlOutput_1 = 0;
				int nb_line_inserted_tMysqlOutput_1 = 0;
				int nb_line_deleted_tMysqlOutput_1 = 0;
				int nb_line_rejected_tMysqlOutput_1 = 0;

				int deletedCount_tMysqlOutput_1 = 0;
				int updatedCount_tMysqlOutput_1 = 0;
				int insertedCount_tMysqlOutput_1 = 0;

				int rejectedCount_tMysqlOutput_1 = 0;

				String tableName_tMysqlOutput_1 = "clientdata_ga_raw";
				boolean whetherReject_tMysqlOutput_1 = false;

				java.util.Calendar calendar_tMysqlOutput_1 = java.util.Calendar
						.getInstance();
				calendar_tMysqlOutput_1.set(1, 0, 1, 0, 0, 0);
				long year1_tMysqlOutput_1 = calendar_tMysqlOutput_1.getTime()
						.getTime();
				calendar_tMysqlOutput_1.set(10000, 0, 1, 0, 0, 0);
				long year10000_tMysqlOutput_1 = calendar_tMysqlOutput_1
						.getTime().getTime();
				long date_tMysqlOutput_1;

				java.sql.Connection conn_tMysqlOutput_1 = null;
				conn_tMysqlOutput_1 = (java.sql.Connection) globalMap
						.get("conn_tMysqlConnection_1");
				if (null == conn_tMysqlOutput_1) {
					java.util.Map<String, routines.system.TalendDataSource> dataSources_tMysqlOutput_1 = (java.util.Map<String, routines.system.TalendDataSource>) globalMap
							.get(KEY_DB_DATASOURCES);
					conn_tMysqlOutput_1 = dataSources_tMysqlOutput_1.get("")
							.getConnection();
				}

				int count_tMysqlOutput_1 = 0;

				java.sql.DatabaseMetaData dbMetaData_tMysqlOutput_1 = conn_tMysqlOutput_1
						.getMetaData();
				java.sql.ResultSet rsTable_tMysqlOutput_1 = dbMetaData_tMysqlOutput_1
						.getTables(null, null, null, new String[] { "TABLE" });
				boolean whetherExist_tMysqlOutput_1 = false;
				while (rsTable_tMysqlOutput_1.next()) {
					String table_tMysqlOutput_1 = rsTable_tMysqlOutput_1
							.getString("TABLE_NAME");
					if (table_tMysqlOutput_1
							.equalsIgnoreCase("clientdata_ga_raw")) {
						whetherExist_tMysqlOutput_1 = true;
						break;
					}
				}
				rsTable_tMysqlOutput_1.close();
				if (!whetherExist_tMysqlOutput_1) {
					java.sql.Statement stmtCreate_tMysqlOutput_1 = conn_tMysqlOutput_1
							.createStatement();
					stmtCreate_tMysqlOutput_1
							.execute("CREATE TABLE `"
									+ tableName_tMysqlOutput_1
									+ "`(`profileid` INT(10)   not null ,`date` DATE  not null ,`visits` INT(10)  ,`visitors` INT(10)  ,`visitorType` VARCHAR(0)  ,`isMobile` VARCHAR(0)  ,`medium` VARCHAR(0)  ,`medium_1` VARCHAR(0)  ,`source` VARCHAR(0)  ,`goalCompletionsAll` INT(0)  ,`goalConversionRateAll` FLOAT(0,0)  ,`visitBounceRate` FLOAT(0,0)  ,`avgTimeOnSite` INT(0)  ,`pageviewsPerVisit` INT(0)  ,primary key(`profileid`,`date`))");
					stmtCreate_tMysqlOutput_1.close();
				}

				String insert_tMysqlOutput_1 = "INSERT INTO `"
						+ "clientdata_ga_raw"
						+ "` (`profileid`,`date`,`visits`,`visitors`,`visitorType`,`isMobile`,`medium`,`medium_1`,`source`,`goalCompletionsAll`,`goalConversionRateAll`,`visitBounceRate`,`avgTimeOnSite`,`pageviewsPerVisit`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
				int batchSize_tMysqlOutput_1 = 100;
				int batchSizeCounter_tMysqlOutput_1 = 0;

				java.sql.PreparedStatement pstmt_tMysqlOutput_1 = conn_tMysqlOutput_1
						.prepareStatement(insert_tMysqlOutput_1);

				/**
				 * [tMysqlOutput_1 begin ] stop
				 */

				/**
				 * [tMap_1 begin ] start
				 */

				ok_Hash.put("tMap_1", false);
				start_Hash.put("tMap_1", System.currentTimeMillis());
				currentComponent = "tMap_1";

				int tos_count_tMap_1 = 0;

				// ###############################
				// # Lookup's keys initialization
				// ###############################

				// ###############################
				// # Vars initialization
				class Var__tMap_1__Struct {
					String medium;
				}
				Var__tMap_1__Struct Var__tMap_1 = new Var__tMap_1__Struct();
				// ###############################

				// ###############################
				// # Outputs initialization
				AnalyticsStruct Analytics_tmp = new AnalyticsStruct();
				// ###############################

				/**
				 * [tMap_1 begin ] stop
				 */

				/**
				 * [tGoogleAnalyticsInput_1 begin ] start
				 */

				ok_Hash.put("tGoogleAnalyticsInput_1", false);
				start_Hash.put("tGoogleAnalyticsInput_1",
						System.currentTimeMillis());
				currentComponent = "tGoogleAnalyticsInput_1";

				int tos_count_tGoogleAnalyticsInput_1 = 0;
				// start creating client
				de.cimt.talendcomp.googleanalytics.GoogleAnalyticsInput tGoogleAnalyticsInput_1 = de.cimt.talendcomp.googleanalytics.GoogleAnalyticsInput
						.getFromCache(context.SERVICE_ACCOUNT + ""
								+ "tGoogleAnalyticsInput_1" + jobName);
				if (tGoogleAnalyticsInput_1 == null) {
					tGoogleAnalyticsInput_1 = new de.cimt.talendcomp.googleanalytics.GoogleAnalyticsInput();
					tGoogleAnalyticsInput_1
							.setApplicationName("Fetch Analytics");
					// setup credentials
					tGoogleAnalyticsInput_1
							.setAccountEmail(context.SERVICE_ACCOUNT);
					tGoogleAnalyticsInput_1.setKeyFile(context.KEY_FILE);
					tGoogleAnalyticsInput_1.setTimeoutInSeconds(240);
					tGoogleAnalyticsInput_1.setTimeOffsetMillisToPast(10000);
					tGoogleAnalyticsInput_1.setFetchSize(10000);
					tGoogleAnalyticsInput_1.deliverTotalsDataset(false);
					try {
						// initialize client with private key
						tGoogleAnalyticsInput_1.initializeAnalyticsClient();
					} catch (Exception e) {
						globalMap.put("tGoogleAnalyticsInput_1_ERROR_MESSAGE",
								e.getMessage());
						throw e;
					}
					globalMap.put("tGoogleAnalyticsInput_1",
							tGoogleAnalyticsInput_1);
					de.cimt.talendcomp.googleanalytics.GoogleAnalyticsInput
							.putIntoCache(context.SERVICE_ACCOUNT + ""
									+ "tGoogleAnalyticsInput_1" + jobName,
									tGoogleAnalyticsInput_1);
				}
				// setup query
				tGoogleAnalyticsInput_1.setProfileId(context.GAPROFILE_ID);
				tGoogleAnalyticsInput_1.setStartDate(context.START_DATE);
				// for selecting data for one day, set end date == start date
				tGoogleAnalyticsInput_1.setEndDate(context.START_DATE);
				tGoogleAnalyticsInput_1
						.setDimensions("ga:visitorType,ga:isMobile,ga:medium,ga:source,ga:date");
				tGoogleAnalyticsInput_1
						.setMetrics("ga:visits,ga:visitors,ga:goalCompletionsAll,ga:goalConversionRateAll,ga:visitBounceRate,ga:avgTimeOnSite,ga:pageviewsPerVisit");
				// fire query and fetch first chunk of data
				try {
					// checks also the correctness of result columns
					tGoogleAnalyticsInput_1.executeQuery();
				} catch (Exception e) {
					globalMap.put("tGoogleAnalyticsInput_1_ERROR_MESSAGE",
							e.getMessage());
					throw e;
				}
				// iterate through the data...
				int countLines_tGoogleAnalyticsInput_1 = 0;
				while (true) {
					try {
						// hasNextDataset() executes a new query if needed
						if (tGoogleAnalyticsInput_1.hasNextDataset() == false) {
							break;
						}
					} catch (Exception e) {
						globalMap.put("tGoogleAnalyticsInput_1_ERROR_MESSAGE",
								e.getMessage());
						throw e;
					}
					// next row from results
					java.util.List<String> dataset_tGoogleAnalyticsInput_1 = tGoogleAnalyticsInput_1
							.getNextDataset();
					// create a new row, thats avoid the need of setting
					// attributes to null
					row2 = new row2Struct();
					// fill schema field visitorType
					String tGoogleAnalyticsInput_1_value_0 = dataset_tGoogleAnalyticsInput_1
							.get(0);
					if (tGoogleAnalyticsInput_1_value_0 != null) {
						row2.visitorType = tGoogleAnalyticsInput_1_value_0;
					}
					// fill schema field isMobile
					String tGoogleAnalyticsInput_1_value_1 = dataset_tGoogleAnalyticsInput_1
							.get(1);
					if (tGoogleAnalyticsInput_1_value_1 != null) {
						row2.isMobile = tGoogleAnalyticsInput_1_value_1;
					}
					// fill schema field medium
					String tGoogleAnalyticsInput_1_value_2 = dataset_tGoogleAnalyticsInput_1
							.get(2);
					if (tGoogleAnalyticsInput_1_value_2 != null) {
						row2.medium = tGoogleAnalyticsInput_1_value_2;
					}
					// fill schema field source
					String tGoogleAnalyticsInput_1_value_3 = dataset_tGoogleAnalyticsInput_1
							.get(3);
					if (tGoogleAnalyticsInput_1_value_3 != null) {
						row2.source = tGoogleAnalyticsInput_1_value_3;
					}
					// fill schema field date
					String tGoogleAnalyticsInput_1_value_4 = dataset_tGoogleAnalyticsInput_1
							.get(4);
					if (tGoogleAnalyticsInput_1_value_4 != null) {
						row2.date = tGoogleAnalyticsInput_1_value_4;
					}
					// fill schema field visits
					String tGoogleAnalyticsInput_1_value_5 = dataset_tGoogleAnalyticsInput_1
							.get(5);
					if (tGoogleAnalyticsInput_1_value_5 != null) {
						try {
							row2.visits = (java.lang.Integer) de.cimt.talendcomp.googleanalytics.Util
									.convertToDatatype(
											tGoogleAnalyticsInput_1_value_5,
											"Integer", "en");
						} catch (Exception e) {
							throw new Exception(
									"Convert field: row2.visits value=["
											+ tGoogleAnalyticsInput_1_value_5
											+ "] countLines="
											+ countLines_tGoogleAnalyticsInput_1
											+ " failed:" + e.getMessage(), e);
						}
					}
					// fill schema field visitors
					String tGoogleAnalyticsInput_1_value_6 = dataset_tGoogleAnalyticsInput_1
							.get(6);
					if (tGoogleAnalyticsInput_1_value_6 != null) {
						try {
							row2.visitors = (java.lang.Integer) de.cimt.talendcomp.googleanalytics.Util
									.convertToDatatype(
											tGoogleAnalyticsInput_1_value_6,
											"Integer", "en");
						} catch (Exception e) {
							throw new Exception(
									"Convert field: row2.visitors value=["
											+ tGoogleAnalyticsInput_1_value_6
											+ "] countLines="
											+ countLines_tGoogleAnalyticsInput_1
											+ " failed:" + e.getMessage(), e);
						}
					}
					// fill schema field goalCompletionsAll
					String tGoogleAnalyticsInput_1_value_7 = dataset_tGoogleAnalyticsInput_1
							.get(7);
					if (tGoogleAnalyticsInput_1_value_7 != null) {
						try {
							row2.goalCompletionsAll = (java.lang.Integer) de.cimt.talendcomp.googleanalytics.Util
									.convertToDatatype(
											tGoogleAnalyticsInput_1_value_7,
											"Integer", "en");
						} catch (Exception e) {
							throw new Exception(
									"Convert field: row2.goalCompletionsAll value=["
											+ tGoogleAnalyticsInput_1_value_7
											+ "] countLines="
											+ countLines_tGoogleAnalyticsInput_1
											+ " failed:" + e.getMessage(), e);
						}
					}
					// fill schema field goalConversionRateAll
					String tGoogleAnalyticsInput_1_value_8 = dataset_tGoogleAnalyticsInput_1
							.get(8);
					if (tGoogleAnalyticsInput_1_value_8 != null) {
						try {
							row2.goalConversionRateAll = (java.lang.Float) de.cimt.talendcomp.googleanalytics.Util
									.convertToDatatype(
											tGoogleAnalyticsInput_1_value_8,
											"Float", "en");
						} catch (Exception e) {
							throw new Exception(
									"Convert field: row2.goalConversionRateAll value=["
											+ tGoogleAnalyticsInput_1_value_8
											+ "] countLines="
											+ countLines_tGoogleAnalyticsInput_1
											+ " failed:" + e.getMessage(), e);
						}
					}
					// fill schema field visitBounceRate
					String tGoogleAnalyticsInput_1_value_9 = dataset_tGoogleAnalyticsInput_1
							.get(9);
					if (tGoogleAnalyticsInput_1_value_9 != null) {
						try {
							row2.visitBounceRate = (java.lang.Float) de.cimt.talendcomp.googleanalytics.Util
									.convertToDatatype(
											tGoogleAnalyticsInput_1_value_9,
											"Float", "en");
						} catch (Exception e) {
							throw new Exception(
									"Convert field: row2.visitBounceRate value=["
											+ tGoogleAnalyticsInput_1_value_9
											+ "] countLines="
											+ countLines_tGoogleAnalyticsInput_1
											+ " failed:" + e.getMessage(), e);
						}
					}
					// fill schema field avgTimeOnSite
					String tGoogleAnalyticsInput_1_value_10 = dataset_tGoogleAnalyticsInput_1
							.get(10);
					if (tGoogleAnalyticsInput_1_value_10 != null) {
						try {
							row2.avgTimeOnSite = (java.lang.Integer) de.cimt.talendcomp.googleanalytics.Util
									.convertToDatatype(
											tGoogleAnalyticsInput_1_value_10,
											"Integer", "en");
						} catch (Exception e) {
							throw new Exception(
									"Convert field: row2.avgTimeOnSite value=["
											+ tGoogleAnalyticsInput_1_value_10
											+ "] countLines="
											+ countLines_tGoogleAnalyticsInput_1
											+ " failed:" + e.getMessage(), e);
						}
					}
					// fill schema field pageviewsPerVisit
					String tGoogleAnalyticsInput_1_value_11 = dataset_tGoogleAnalyticsInput_1
							.get(11);
					if (tGoogleAnalyticsInput_1_value_11 != null) {
						try {
							row2.pageviewsPerVisit = (java.lang.Integer) de.cimt.talendcomp.googleanalytics.Util
									.convertToDatatype(
											tGoogleAnalyticsInput_1_value_11,
											"Integer", "en");
						} catch (Exception e) {
							throw new Exception(
									"Convert field: row2.pageviewsPerVisit value=["
											+ tGoogleAnalyticsInput_1_value_11
											+ "] countLines="
											+ countLines_tGoogleAnalyticsInput_1
											+ " failed:" + e.getMessage(), e);
						}
					}

					/**
					 * [tGoogleAnalyticsInput_1 begin ] stop
					 */
					/**
					 * [tGoogleAnalyticsInput_1 main ] start
					 */

					currentComponent = "tGoogleAnalyticsInput_1";

					tos_count_tGoogleAnalyticsInput_1++;

					/**
					 * [tGoogleAnalyticsInput_1 main ] stop
					 */

					/**
					 * [tMap_1 main ] start
					 */

					currentComponent = "tMap_1";

					boolean hasCasePrimitiveKeyWithNull_tMap_1 = false;

					// ###############################
					// # Input tables (lookups)
					boolean rejectedInnerJoin_tMap_1 = false;
					boolean mainRowRejected_tMap_1 = false;

					// ###############################
					{ // start of Var scope

						// ###############################
						// # Vars tables

						Var__tMap_1__Struct Var = Var__tMap_1;
						Var.medium = row2.medium != null
								&& row2.medium.trim().length() > 0 ? StringHandling
								.DOWNCASE(row2.medium) : "";// ###############################
						// ###############################
						// # Output tables

						Analytics = null;

						// # Output table : 'Analytics'
						Analytics_tmp.profileid = Integer
								.parseInt(context.GAPROFILE_ID);
						Analytics_tmp.date = TalendDate.parseDate("yyyyMMdd",
								row2.date);
						Analytics_tmp.visits = row2.visits;
						Analytics_tmp.visitors = row2.visitors

						;
						Analytics_tmp.visitorType = row2.visitorType;
						Analytics_tmp.isMobile = row2.isMobile;
						Analytics_tmp.medium = Var.medium.equals("") ? ""
								: islabs_ga_common
										.cleanseMediumData(Var.medium);
						Analytics_tmp.medium_1 = row2.medium;
						Analytics_tmp.source = row2.source;
						Analytics_tmp.goalCompletionsAll = row2.goalCompletionsAll;
						Analytics_tmp.goalConversionRateAll = row2.goalConversionRateAll;
						Analytics_tmp.visitBounceRate = row2.visitBounceRate;
						Analytics_tmp.avgTimeOnSite = row2.avgTimeOnSite;
						Analytics_tmp.pageviewsPerVisit = row2.pageviewsPerVisit;
						Analytics = Analytics_tmp;
						// ###############################

					} // end of Var scope

					rejectedInnerJoin_tMap_1 = false;

					tos_count_tMap_1++;

					/**
					 * [tMap_1 main ] stop
					 */
					// Start of branch "Analytics"
					if (Analytics != null) {

						/**
						 * [tMysqlOutput_1 main ] start
						 */

						currentComponent = "tMysqlOutput_1";

						whetherReject_tMysqlOutput_1 = false;
						pstmt_tMysqlOutput_1.setInt(1, Analytics.profileid);

						if (Analytics.date != null) {
							date_tMysqlOutput_1 = Analytics.date.getTime();
							if (date_tMysqlOutput_1 < year1_tMysqlOutput_1
									|| date_tMysqlOutput_1 >= year10000_tMysqlOutput_1) {
								pstmt_tMysqlOutput_1.setString(2,
										"0000-00-00 00:00:00");
							} else {
								pstmt_tMysqlOutput_1.setTimestamp(2,
										new java.sql.Timestamp(
												date_tMysqlOutput_1));
							}
						} else {
							pstmt_tMysqlOutput_1
									.setNull(2, java.sql.Types.DATE);
						}

						if (Analytics.visits == null) {
							pstmt_tMysqlOutput_1.setNull(3,
									java.sql.Types.INTEGER);
						} else {
							pstmt_tMysqlOutput_1.setInt(3, Analytics.visits);
						}

						if (Analytics.visitors == null) {
							pstmt_tMysqlOutput_1.setNull(4,
									java.sql.Types.INTEGER);
						} else {
							pstmt_tMysqlOutput_1.setInt(4, Analytics.visitors);
						}

						if (Analytics.visitorType == null) {
							pstmt_tMysqlOutput_1.setNull(5,
									java.sql.Types.VARCHAR);
						} else {
							pstmt_tMysqlOutput_1.setString(5,
									Analytics.visitorType);
						}

						if (Analytics.isMobile == null) {
							pstmt_tMysqlOutput_1.setNull(6,
									java.sql.Types.VARCHAR);
						} else {
							pstmt_tMysqlOutput_1.setString(6,
									Analytics.isMobile);
						}

						if (Analytics.medium == null) {
							pstmt_tMysqlOutput_1.setNull(7,
									java.sql.Types.VARCHAR);
						} else {
							pstmt_tMysqlOutput_1.setString(7, Analytics.medium);
						}

						if (Analytics.medium_1 == null) {
							pstmt_tMysqlOutput_1.setNull(8,
									java.sql.Types.VARCHAR);
						} else {
							pstmt_tMysqlOutput_1.setString(8,
									Analytics.medium_1);
						}

						if (Analytics.source == null) {
							pstmt_tMysqlOutput_1.setNull(9,
									java.sql.Types.VARCHAR);
						} else {
							pstmt_tMysqlOutput_1.setString(9, Analytics.source);
						}

						if (Analytics.goalCompletionsAll == null) {
							pstmt_tMysqlOutput_1.setNull(10,
									java.sql.Types.INTEGER);
						} else {
							pstmt_tMysqlOutput_1.setInt(10,
									Analytics.goalCompletionsAll);
						}

						if (Analytics.goalConversionRateAll == null) {
							pstmt_tMysqlOutput_1.setNull(11,
									java.sql.Types.FLOAT);
						} else {
							pstmt_tMysqlOutput_1.setFloat(11,
									Analytics.goalConversionRateAll);
						}

						if (Analytics.visitBounceRate == null) {
							pstmt_tMysqlOutput_1.setNull(12,
									java.sql.Types.FLOAT);
						} else {
							pstmt_tMysqlOutput_1.setFloat(12,
									Analytics.visitBounceRate);
						}

						if (Analytics.avgTimeOnSite == null) {
							pstmt_tMysqlOutput_1.setNull(13,
									java.sql.Types.INTEGER);
						} else {
							pstmt_tMysqlOutput_1.setInt(13,
									Analytics.avgTimeOnSite);
						}

						if (Analytics.pageviewsPerVisit == null) {
							pstmt_tMysqlOutput_1.setNull(14,
									java.sql.Types.INTEGER);
						} else {
							pstmt_tMysqlOutput_1.setInt(14,
									Analytics.pageviewsPerVisit);
						}

						pstmt_tMysqlOutput_1.addBatch();
						nb_line_tMysqlOutput_1++;

						batchSizeCounter_tMysqlOutput_1++;

						if (!whetherReject_tMysqlOutput_1) {
						}
						if (batchSize_tMysqlOutput_1 <= batchSizeCounter_tMysqlOutput_1) {
							try {
								int countSum_tMysqlOutput_1 = 0;
								for (int countEach_tMysqlOutput_1 : pstmt_tMysqlOutput_1
										.executeBatch()) {
									countSum_tMysqlOutput_1 += (countEach_tMysqlOutput_1 < 0 ? 0
											: countEach_tMysqlOutput_1);
								}

								insertedCount_tMysqlOutput_1 += countSum_tMysqlOutput_1;

							} catch (java.sql.BatchUpdateException e) {

								throw (e);

							}

							batchSizeCounter_tMysqlOutput_1 = 0;
						}

						tos_count_tMysqlOutput_1++;

						/**
						 * [tMysqlOutput_1 main ] stop
						 */

					} // End of branch "Analytics"

					/**
					 * [tGoogleAnalyticsInput_1 end ] start
					 */

					currentComponent = "tGoogleAnalyticsInput_1";

					countLines_tGoogleAnalyticsInput_1++;
				} // close while from output connection of
					// tGoogleAnalyticsInput_1
				globalMap.put("tGoogleAnalyticsInput_1_NB_LINE",
						countLines_tGoogleAnalyticsInput_1);
				globalMap.put("tGoogleAnalyticsInput_1_TOTAL_AFFECTED_ROWS",
						tGoogleAnalyticsInput_1.getTotalAffectedRows());
				globalMap.put("tGoogleAnalyticsInput_1_CONTAINS_SAMPLED_DATA",
						tGoogleAnalyticsInput_1.containsSampledData());

				ok_Hash.put("tGoogleAnalyticsInput_1", true);
				end_Hash.put("tGoogleAnalyticsInput_1",
						System.currentTimeMillis());

				/**
				 * [tGoogleAnalyticsInput_1 end ] stop
				 */

				/**
				 * [tMap_1 end ] start
				 */

				currentComponent = "tMap_1";

				// ###############################
				// # Lookup hashes releasing
				// ###############################

				ok_Hash.put("tMap_1", true);
				end_Hash.put("tMap_1", System.currentTimeMillis());

				/**
				 * [tMap_1 end ] stop
				 */

				/**
				 * [tMysqlOutput_1 end ] start
				 */

				currentComponent = "tMysqlOutput_1";

				try {
					if (batchSizeCounter_tMysqlOutput_1 != 0) {
						int countSum_tMysqlOutput_1 = 0;
						for (int countEach_tMysqlOutput_1 : pstmt_tMysqlOutput_1
								.executeBatch()) {
							countSum_tMysqlOutput_1 += (countEach_tMysqlOutput_1 < 0 ? 0
									: countEach_tMysqlOutput_1);
						}

						insertedCount_tMysqlOutput_1 += countSum_tMysqlOutput_1;

					}

				} catch (java.sql.BatchUpdateException e) {

					throw (e);

				}
				batchSizeCounter_tMysqlOutput_1 = 0;

				try {
					if (pstmt_tMysqlOutput_1 != null) {
						int countSum_tMysqlOutput_1 = 0;
						for (int countEach_tMysqlOutput_1 : pstmt_tMysqlOutput_1
								.executeBatch()) {
							countSum_tMysqlOutput_1 += (countEach_tMysqlOutput_1 < 0 ? 0
									: countEach_tMysqlOutput_1);
						}

						insertedCount_tMysqlOutput_1 += countSum_tMysqlOutput_1;

					}
				} catch (java.sql.BatchUpdateException e) {

					throw (e);

				}

				if (pstmt_tMysqlOutput_1 != null) {

					pstmt_tMysqlOutput_1.close();

				}

				nb_line_deleted_tMysqlOutput_1 = nb_line_deleted_tMysqlOutput_1
						+ deletedCount_tMysqlOutput_1;
				nb_line_update_tMysqlOutput_1 = nb_line_update_tMysqlOutput_1
						+ updatedCount_tMysqlOutput_1;
				nb_line_inserted_tMysqlOutput_1 = nb_line_inserted_tMysqlOutput_1
						+ insertedCount_tMysqlOutput_1;
				nb_line_rejected_tMysqlOutput_1 = nb_line_rejected_tMysqlOutput_1
						+ rejectedCount_tMysqlOutput_1;

				globalMap.put("tMysqlOutput_1_NB_LINE", nb_line_tMysqlOutput_1);
				globalMap.put("tMysqlOutput_1_NB_LINE_UPDATED",
						nb_line_update_tMysqlOutput_1);
				globalMap.put("tMysqlOutput_1_NB_LINE_INSERTED",
						nb_line_inserted_tMysqlOutput_1);
				globalMap.put("tMysqlOutput_1_NB_LINE_DELETED",
						nb_line_deleted_tMysqlOutput_1);
				globalMap.put("tMysqlOutput_1_NB_LINE_REJECTED",
						nb_line_rejected_tMysqlOutput_1);

				ok_Hash.put("tMysqlOutput_1", true);
				end_Hash.put("tMysqlOutput_1", System.currentTimeMillis());

				tMysqlCommit_1Process(globalMap);

				/**
				 * [tMysqlOutput_1 end ] stop
				 */

			}// end the resume

		} catch (java.lang.Exception e) {

			throw new TalendException(e, currentComponent, globalMap);

		} catch (java.lang.Error error) {

			throw error;

		}

		globalMap.put("tGoogleAnalyticsInput_1_SUBPROCESS_STATE", 1);
	}

	public void tMysqlCommit_1Process(
			final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tMysqlCommit_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";
		int iterateLoop = 0;
		String currentComponent = "";

		try {

			String currentMethodName = new java.lang.Exception()
					.getStackTrace()[0].getMethodName();
			boolean resumeIt = currentMethodName.equals(resumeEntryMethodName);
			if (resumeEntryMethodName == null || resumeIt || globalResumeTicket) {// start
																					// the
																					// resume
				globalResumeTicket = true;

				/**
				 * [tMysqlCommit_1 begin ] start
				 */

				ok_Hash.put("tMysqlCommit_1", false);
				start_Hash.put("tMysqlCommit_1", System.currentTimeMillis());
				currentComponent = "tMysqlCommit_1";

				int tos_count_tMysqlCommit_1 = 0;

				/**
				 * [tMysqlCommit_1 begin ] stop
				 */
				/**
				 * [tMysqlCommit_1 main ] start
				 */

				currentComponent = "tMysqlCommit_1";

				java.sql.Connection conn_tMysqlCommit_1 = (java.sql.Connection) globalMap
						.get("conn_tMysqlConnection_1");

				if (null == conn_tMysqlCommit_1) {
					java.util.Map<String, routines.system.TalendDataSource> dataSources_tMysqlCommit_1 = (java.util.Map<String, routines.system.TalendDataSource>) globalMap
							.get(KEY_DB_DATASOURCES);
					if (dataSources_tMysqlCommit_1 != null) {
						if (dataSources_tMysqlCommit_1.get("") != null) {
							conn_tMysqlCommit_1 = dataSources_tMysqlCommit_1
									.get("").getConnection();
						}
					}
				}

				if (conn_tMysqlCommit_1 != null
						&& !conn_tMysqlCommit_1.isClosed()) {
					conn_tMysqlCommit_1.commit();
					conn_tMysqlCommit_1.close();
				}

				tos_count_tMysqlCommit_1++;

				/**
				 * [tMysqlCommit_1 main ] stop
				 */
				/**
				 * [tMysqlCommit_1 end ] start
				 */

				currentComponent = "tMysqlCommit_1";

				ok_Hash.put("tMysqlCommit_1", true);
				end_Hash.put("tMysqlCommit_1", System.currentTimeMillis());

				/**
				 * [tMysqlCommit_1 end ] stop
				 */

			}// end the resume

		} catch (java.lang.Exception e) {

			throw new TalendException(e, currentComponent, globalMap);

		} catch (java.lang.Error error) {

			throw error;

		}

		globalMap.put("tMysqlCommit_1_SUBPROCESS_STATE", 1);
	}

	public static class outStruct implements
			routines.system.IPersistableRow<outStruct> {
		final static byte[] commonByteArrayLock_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[0];
		static byte[] commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[0];

		public java.util.Date moment;

		public java.util.Date getMoment() {
			return this.moment;
		}

		public String job;

		public String getJob() {
			return this.job;
		}

		public String message;

		public String getMessage() {
			return this.message;
		}

		public String GAPROFILE_ID;

		public String getGAPROFILE_ID() {
			return this.GAPROFILE_ID;
		}

		private java.util.Date readDate(ObjectInputStream dis)
				throws IOException {
			java.util.Date dateReturn = null;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				dateReturn = null;
			} else {
				dateReturn = new Date(dis.readLong());
			}
			return dateReturn;
		}

		private void writeDate(java.util.Date date1, ObjectOutputStream dos)
				throws IOException {
			if (date1 == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeLong(date1.getTime());
			}
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data.length) {
					if (length < 1024
							&& commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data.length == 0) {
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[1024];
					} else {
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[2 * length];
					}
				}
				dis.readFully(
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data,
						0, length);
				strReturn = new String(
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data,
						0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos)
				throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data) {

				try {

					int length = 0;

					this.moment = readDate(dis);

					this.job = readString(dis);

					this.message = readString(dis);

					this.GAPROFILE_ID = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// java.util.Date

				writeDate(this.moment, dos);

				// String

				writeString(this.job, dos);

				// String

				writeString(this.message, dos);

				// String

				writeString(this.GAPROFILE_ID, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("moment=" + String.valueOf(moment));
			sb.append(",job=" + job);
			sb.append(",message=" + message);
			sb.append(",GAPROFILE_ID=" + GAPROFILE_ID);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(outStruct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(),
						object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public static class row1Struct implements
			routines.system.IPersistableRow<row1Struct> {
		final static byte[] commonByteArrayLock_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[0];
		static byte[] commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[0];

		public java.util.Date moment;

		public java.util.Date getMoment() {
			return this.moment;
		}

		public String pid;

		public String getPid() {
			return this.pid;
		}

		public String root_pid;

		public String getRoot_pid() {
			return this.root_pid;
		}

		public String father_pid;

		public String getFather_pid() {
			return this.father_pid;
		}

		public String project;

		public String getProject() {
			return this.project;
		}

		public String job;

		public String getJob() {
			return this.job;
		}

		public String context;

		public String getContext() {
			return this.context;
		}

		public Integer priority;

		public Integer getPriority() {
			return this.priority;
		}

		public String type;

		public String getType() {
			return this.type;
		}

		public String origin;

		public String getOrigin() {
			return this.origin;
		}

		public String message;

		public String getMessage() {
			return this.message;
		}

		public Integer code;

		public Integer getCode() {
			return this.code;
		}

		private java.util.Date readDate(ObjectInputStream dis)
				throws IOException {
			java.util.Date dateReturn = null;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				dateReturn = null;
			} else {
				dateReturn = new Date(dis.readLong());
			}
			return dateReturn;
		}

		private void writeDate(java.util.Date date1, ObjectOutputStream dos)
				throws IOException {
			if (date1 == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeLong(date1.getTime());
			}
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data.length) {
					if (length < 1024
							&& commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data.length == 0) {
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[1024];
					} else {
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data = new byte[2 * length];
					}
				}
				dis.readFully(
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data,
						0, length);
				strReturn = new String(
						commonByteArray_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data,
						0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos)
				throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		private Integer readInteger(ObjectInputStream dis) throws IOException {
			Integer intReturn;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				intReturn = null;
			} else {
				intReturn = dis.readInt();
			}
			return intReturn;
		}

		private void writeInteger(Integer intNum, ObjectOutputStream dos)
				throws IOException {
			if (intNum == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeInt(intNum);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_ISLABS_MVMETRICS_Dymanically_Fetching_GA_Data) {

				try {

					int length = 0;

					this.moment = readDate(dis);

					this.pid = readString(dis);

					this.root_pid = readString(dis);

					this.father_pid = readString(dis);

					this.project = readString(dis);

					this.job = readString(dis);

					this.context = readString(dis);

					this.priority = readInteger(dis);

					this.type = readString(dis);

					this.origin = readString(dis);

					this.message = readString(dis);

					this.code = readInteger(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// java.util.Date

				writeDate(this.moment, dos);

				// String

				writeString(this.pid, dos);

				// String

				writeString(this.root_pid, dos);

				// String

				writeString(this.father_pid, dos);

				// String

				writeString(this.project, dos);

				// String

				writeString(this.job, dos);

				// String

				writeString(this.context, dos);

				// Integer

				writeInteger(this.priority, dos);

				// String

				writeString(this.type, dos);

				// String

				writeString(this.origin, dos);

				// String

				writeString(this.message, dos);

				// Integer

				writeInteger(this.code, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("moment=" + String.valueOf(moment));
			sb.append(",pid=" + pid);
			sb.append(",root_pid=" + root_pid);
			sb.append(",father_pid=" + father_pid);
			sb.append(",project=" + project);
			sb.append(",job=" + job);
			sb.append(",context=" + context);
			sb.append(",priority=" + String.valueOf(priority));
			sb.append(",type=" + type);
			sb.append(",origin=" + origin);
			sb.append(",message=" + message);
			sb.append(",code=" + String.valueOf(code));
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row1Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(),
						object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void tLogCatcher_1Process(
			final java.util.Map<String, Object> globalMap)
			throws TalendException {
		globalMap.put("tLogCatcher_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";
		int iterateLoop = 0;
		String currentComponent = "";

		try {

			String currentMethodName = new java.lang.Exception()
					.getStackTrace()[0].getMethodName();
			boolean resumeIt = currentMethodName.equals(resumeEntryMethodName);
			if (resumeEntryMethodName == null || resumeIt || globalResumeTicket) {// start
																					// the
																					// resume
				globalResumeTicket = true;

				row1Struct row1 = new row1Struct();
				outStruct out = new outStruct();

				/**
				 * [tFileOutputDelimited_1 begin ] start
				 */

				ok_Hash.put("tFileOutputDelimited_1", false);
				start_Hash.put("tFileOutputDelimited_1",
						System.currentTimeMillis());
				currentComponent = "tFileOutputDelimited_1";

				int tos_count_tFileOutputDelimited_1 = 0;

				String fileName_tFileOutputDelimited_1 = "";
				fileName_tFileOutputDelimited_1 = (new java.io.File(
						context.LOG_FILE_DIR + "/populate_client_data_"
								+ context.CURRENT_DATE + ".log"))
						.getAbsolutePath().replace("\\", "/");
				String fullName_tFileOutputDelimited_1 = null;
				String extension_tFileOutputDelimited_1 = null;
				String directory_tFileOutputDelimited_1 = null;
				if ((fileName_tFileOutputDelimited_1.indexOf("/") != -1)) {
					if (fileName_tFileOutputDelimited_1.lastIndexOf(".") < fileName_tFileOutputDelimited_1
							.lastIndexOf("/")) {
						fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1;
						extension_tFileOutputDelimited_1 = "";
					} else {
						fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
								.substring(0, fileName_tFileOutputDelimited_1
										.lastIndexOf("."));
						extension_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
								.substring(fileName_tFileOutputDelimited_1
										.lastIndexOf("."));
					}
					directory_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
							.substring(0, fileName_tFileOutputDelimited_1
									.lastIndexOf("/"));
				} else {
					if (fileName_tFileOutputDelimited_1.lastIndexOf(".") != -1) {
						fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
								.substring(0, fileName_tFileOutputDelimited_1
										.lastIndexOf("."));
						extension_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1
								.substring(fileName_tFileOutputDelimited_1
										.lastIndexOf("."));
					} else {
						fullName_tFileOutputDelimited_1 = fileName_tFileOutputDelimited_1;
						extension_tFileOutputDelimited_1 = "";
					}
					directory_tFileOutputDelimited_1 = "";
				}
				boolean isFileGenerated_tFileOutputDelimited_1 = true;
				java.io.File filetFileOutputDelimited_1 = new java.io.File(
						fileName_tFileOutputDelimited_1);
				globalMap.put("tFileOutputDelimited_1_FILE_NAME",
						fileName_tFileOutputDelimited_1);
				if (filetFileOutputDelimited_1.exists()) {
					isFileGenerated_tFileOutputDelimited_1 = false;
				}

				int nb_line_tFileOutputDelimited_1 = 0;
				int splitEvery_tFileOutputDelimited_1 = 1000;
				int splitedFileNo_tFileOutputDelimited_1 = 0;
				int currentRow_tFileOutputDelimited_1 = 0;

				final String OUT_DELIM_tFileOutputDelimited_1 = /**
				 * Start field
				 * tFileOutputDelimited_1:FIELDSEPARATOR
				 */
				";"/** End field tFileOutputDelimited_1:FIELDSEPARATOR */
				;

				final String OUT_DELIM_ROWSEP_tFileOutputDelimited_1 = /**
				 * Start
				 * field tFileOutputDelimited_1:ROWSEPARATOR
				 */
				"\n"/** End field tFileOutputDelimited_1:ROWSEPARATOR */
				;

				// create directory only if not exists
				if (directory_tFileOutputDelimited_1 != null
						&& directory_tFileOutputDelimited_1.trim().length() != 0) {
					java.io.File dir_tFileOutputDelimited_1 = new java.io.File(
							directory_tFileOutputDelimited_1);
					if (!dir_tFileOutputDelimited_1.exists()) {
						dir_tFileOutputDelimited_1.mkdirs();
					}
				}

				// routines.system.Row
				java.io.Writer outtFileOutputDelimited_1 = null;
				try {
					outtFileOutputDelimited_1 = new java.io.BufferedWriter(
							new java.io.OutputStreamWriter(
									new java.io.FileOutputStream(
											fileName_tFileOutputDelimited_1,
											true), "ISO-8859-15"));

					if (filetFileOutputDelimited_1.length() == 0) {

						outtFileOutputDelimited_1.write("moment");

						outtFileOutputDelimited_1
								.write(OUT_DELIM_tFileOutputDelimited_1);

						outtFileOutputDelimited_1.write("job");

						outtFileOutputDelimited_1
								.write(OUT_DELIM_tFileOutputDelimited_1);

						outtFileOutputDelimited_1.write("message");

						outtFileOutputDelimited_1
								.write(OUT_DELIM_tFileOutputDelimited_1);

						outtFileOutputDelimited_1.write("GAPROFILE_ID");

						outtFileOutputDelimited_1
								.write(OUT_DELIM_ROWSEP_tFileOutputDelimited_1);
						outtFileOutputDelimited_1.flush();
					}

					/**
					 * [tFileOutputDelimited_1 begin ] stop
					 */

					/**
					 * [tMap_2 begin ] start
					 */

					ok_Hash.put("tMap_2", false);
					start_Hash.put("tMap_2", System.currentTimeMillis());
					currentComponent = "tMap_2";

					int tos_count_tMap_2 = 0;

					// ###############################
					// # Lookup's keys initialization
					// ###############################

					// ###############################
					// # Vars initialization
					class Var__tMap_2__Struct {
					}
					Var__tMap_2__Struct Var__tMap_2 = new Var__tMap_2__Struct();
					// ###############################

					// ###############################
					// # Outputs initialization
					outStruct out_tmp = new outStruct();
					// ###############################

					/**
					 * [tMap_2 begin ] stop
					 */

					/**
					 * [tLogCatcher_1 begin ] start
					 */

					ok_Hash.put("tLogCatcher_1", false);
					start_Hash.put("tLogCatcher_1", System.currentTimeMillis());
					currentComponent = "tLogCatcher_1";

					int tos_count_tLogCatcher_1 = 0;

					for (LogCatcherUtils.LogCatcherMessage lcm : tLogCatcher_1
							.getMessages()) {
						row1.type = lcm.getType();
						row1.origin = (lcm.getOrigin() == null
								|| lcm.getOrigin().length() < 1 ? null : lcm
								.getOrigin());
						row1.priority = lcm.getPriority();
						row1.message = lcm.getMessage();
						row1.code = lcm.getCode();

						row1.moment = java.util.Calendar.getInstance()
								.getTime();

						row1.pid = pid;
						row1.root_pid = rootPid;
						row1.father_pid = fatherPid;

						row1.project = projectName;
						row1.job = jobName;
						row1.context = contextStr;

						/**
						 * [tLogCatcher_1 begin ] stop
						 */
						/**
						 * [tLogCatcher_1 main ] start
						 */

						currentComponent = "tLogCatcher_1";

						tos_count_tLogCatcher_1++;

						/**
						 * [tLogCatcher_1 main ] stop
						 */

						/**
						 * [tMap_2 main ] start
						 */

						currentComponent = "tMap_2";

						boolean hasCasePrimitiveKeyWithNull_tMap_2 = false;

						// ###############################
						// # Input tables (lookups)
						boolean rejectedInnerJoin_tMap_2 = false;
						boolean mainRowRejected_tMap_2 = false;

						// ###############################
						{ // start of Var scope

							// ###############################
							// # Vars tables

							Var__tMap_2__Struct Var = Var__tMap_2;// ###############################
							// ###############################
							// # Output tables

							out = null;

							// # Output table : 'out'
							out_tmp.moment = row1.moment;
							out_tmp.job = row1.job;
							out_tmp.message = row1.message;
							out_tmp.GAPROFILE_ID = context.GAPROFILE_ID;
							out = out_tmp;
							// ###############################

						} // end of Var scope

						rejectedInnerJoin_tMap_2 = false;

						tos_count_tMap_2++;

						/**
						 * [tMap_2 main ] stop
						 */
						// Start of branch "out"
						if (out != null) {

							/**
							 * [tFileOutputDelimited_1 main ] start
							 */

							currentComponent = "tFileOutputDelimited_1";

							StringBuilder sb_tFileOutputDelimited_1 = new StringBuilder();

							if (out.moment != null) {

								sb_tFileOutputDelimited_1.append(

								FormatterUtils.format_Date(out.moment,
										"yyyy-MM-dd HH:mm:ss")

								);

							}

							sb_tFileOutputDelimited_1
									.append(OUT_DELIM_tFileOutputDelimited_1);

							if (out.job != null) {

								sb_tFileOutputDelimited_1.append(

								out.job

								);

							}

							sb_tFileOutputDelimited_1
									.append(OUT_DELIM_tFileOutputDelimited_1);

							if (out.message != null) {

								sb_tFileOutputDelimited_1.append(

								out.message

								);

							}

							sb_tFileOutputDelimited_1
									.append(OUT_DELIM_tFileOutputDelimited_1);

							if (out.GAPROFILE_ID != null) {

								sb_tFileOutputDelimited_1.append(

								out.GAPROFILE_ID

								);

							}

							sb_tFileOutputDelimited_1
									.append(OUT_DELIM_ROWSEP_tFileOutputDelimited_1);

							nb_line_tFileOutputDelimited_1++;

							outtFileOutputDelimited_1
									.write(sb_tFileOutputDelimited_1.toString());

							tos_count_tFileOutputDelimited_1++;

							/**
							 * [tFileOutputDelimited_1 main ] stop
							 */

						} // End of branch "out"

						/**
						 * [tLogCatcher_1 end ] start
						 */

						currentComponent = "tLogCatcher_1";

					}

					ok_Hash.put("tLogCatcher_1", true);
					end_Hash.put("tLogCatcher_1", System.currentTimeMillis());

					/**
					 * [tLogCatcher_1 end ] stop
					 */

					/**
					 * [tMap_2 end ] start
					 */

					currentComponent = "tMap_2";

					// ###############################
					// # Lookup hashes releasing
					// ###############################

					ok_Hash.put("tMap_2", true);
					end_Hash.put("tMap_2", System.currentTimeMillis());

					/**
					 * [tMap_2 end ] stop
					 */

					/**
					 * [tFileOutputDelimited_1 end ] start
					 */

					currentComponent = "tFileOutputDelimited_1";

				} finally {
					if (outtFileOutputDelimited_1 != null) {
						outtFileOutputDelimited_1.flush();
						outtFileOutputDelimited_1.close();
					}
					globalMap.put("tFileOutputDelimited_1_NB_LINE",
							nb_line_tFileOutputDelimited_1);
					globalMap.put("tFileOutputDelimited_1_FILE_NAME",
							fileName_tFileOutputDelimited_1);
				} // finally

				ok_Hash.put("tFileOutputDelimited_1", true);
				end_Hash.put("tFileOutputDelimited_1",
						System.currentTimeMillis());

				/**
				 * [tFileOutputDelimited_1 end ] stop
				 */

			}// end the resume

		} catch (java.lang.Exception e) {

			throw new TalendException(e, currentComponent, globalMap);

		} catch (java.lang.Error error) {

			throw error;

		}

		globalMap.put("tLogCatcher_1_SUBPROCESS_STATE", 1);
	}

	public String resuming_logs_dir_path = null;
	public String resuming_checkpoint_path = null;
	public String parent_part_launcher = null;
	private String resumeEntryMethodName = null;
	private boolean globalResumeTicket = false;

	public boolean watch = false;
	// portStats is null, it means don't execute the statistics
	public Integer portStats = null;
	public int portTraces = 4334;
	public String clientHost;
	public String defaultClientHost = "localhost";
	public String contextStr = "Default";
	public boolean isDefaultContext = true;
	public String pid = "0";
	public String rootPid = null;
	public String fatherPid = null;
	public String fatherNode = null;
	public long startTime = 0;
	public boolean isChildJob = false;

	private boolean execStat = true;

	private ThreadLocal<java.util.Map<String, String>> threadLocal = new ThreadLocal<java.util.Map<String, String>>() {
		protected java.util.Map<String, String> initialValue() {
			java.util.Map<String, String> threadRunResultMap = new java.util.HashMap<String, String>();
			threadRunResultMap.put("errorCode", null);
			threadRunResultMap.put("status", "");
			return threadRunResultMap;
		};
	};

	private java.util.Properties context_param = new java.util.Properties();
	public java.util.Map<String, Object> parentContextMap = new java.util.HashMap<String, Object>();

	public String status = "";

	public static void main(String[] args) {
		final Dymanically_Fetching_GA_Data Dymanically_Fetching_GA_DataClass = new Dymanically_Fetching_GA_Data();

		int exitCode = Dymanically_Fetching_GA_DataClass.runJobInTOS(args);
		System.exit(exitCode);
	}

	public String[][] runJob(String[] args) {

		int exitCode = runJobInTOS(args);
		String[][] bufferValue = new String[][] { { Integer.toString(exitCode) } };

		return bufferValue;
	}

	public int runJobInTOS(String[] args) {
		// reset status
		status = "";

		String lastStr = "";
		for (String arg : args) {
			if (arg.equalsIgnoreCase("--context_param")) {
				lastStr = arg;
			} else if (lastStr.equals("")) {
				evalParam(arg);
			} else {
				evalParam(lastStr + " " + arg);
				lastStr = "";
			}
		}

		if (clientHost == null) {
			clientHost = defaultClientHost;
		}

		if (pid == null || "0".equals(pid)) {
			pid = TalendString.getAsciiRandomString(6);
		}

		if (rootPid == null) {
			rootPid = pid;
		}
		if (fatherPid == null) {
			fatherPid = pid;
		} else {
			isChildJob = true;
		}

		try {
			// call job/subjob with an existing context, like:
			// --context=production. if without this parameter, there will use
			// the default context instead.
			java.io.InputStream inContext = Dymanically_Fetching_GA_Data.class
					.getClassLoader().getResourceAsStream(
							"islabs_mvmetrics/dymanically_fetching_ga_data_0_1/contexts/"
									+ contextStr + ".properties");
			if (isDefaultContext && inContext == null) {

			} else {
				if (inContext != null) {
					// defaultProps is in order to keep the original context
					// value
					defaultProps.load(inContext);
					inContext.close();
					context = new ContextProperties(defaultProps);
				} else {
					// print info and job continue to run, for case:
					// context_param is not empty.
					System.err.println("Could not find the context "
							+ contextStr);
				}
			}

			if (!context_param.isEmpty()) {
				context.putAll(context_param);
			}
			context.END_DATE = (String) context.getProperty("END_DATE");
			context.START_DATE = (String) context.getProperty("START_DATE");
			context.CONN_HOST = (String) context.getProperty("CONN_HOST");
			context.PORT = (String) context.getProperty("PORT");
			context.DATABASE = (String) context.getProperty("DATABASE");
			context.USER_NAME = (String) context.getProperty("USER_NAME");
			context.PASSWORD = (String) context.getProperty("PASSWORD");
			context.SERVICE_ACCOUNT = (String) context
					.getProperty("SERVICE_ACCOUNT");
			context.KEY_FILE = (String) context.getProperty("KEY_FILE");
			context.PROFILE_ID = (String) context.getProperty("PROFILE_ID");
			context.GAPROFILE_ID = (String) context.getProperty("GAPROFILE_ID");
			context.LOG_FILE_DIR = (String) context.getProperty("LOG_FILE_DIR");
			context.CURRENT_DATE = (String) context.getProperty("CURRENT_DATE");
			context.DynamicFetch_AdditionalParams = (String) context
					.getProperty("DynamicFetch_AdditionalParams");
			context.DynamicFetch_Login = (String) context
					.getProperty("DynamicFetch_Login");
			context.DynamicFetch_Database = (String) context
					.getProperty("DynamicFetch_Database");
			context.DynamicFetch_Password = (java.lang.String) context
					.getProperty("DynamicFetch_Password");
			context.DynamicFetch_Server = (String) context
					.getProperty("DynamicFetch_Server");
			context.DynamicFetch_Port = (String) context
					.getProperty("DynamicFetch_Port");
		} catch (java.io.IOException ie) {
			System.err.println("Could not load context " + contextStr);
			ie.printStackTrace();
		}

		// get context value from parent directly
		if (parentContextMap != null && !parentContextMap.isEmpty()) {
			if (parentContextMap.containsKey("END_DATE")) {
				context.END_DATE = (String) parentContextMap.get("END_DATE");
			}
			if (parentContextMap.containsKey("START_DATE")) {
				context.START_DATE = (String) parentContextMap
						.get("START_DATE");
			}
			if (parentContextMap.containsKey("CONN_HOST")) {
				context.CONN_HOST = (String) parentContextMap.get("CONN_HOST");
			}
			if (parentContextMap.containsKey("PORT")) {
				context.PORT = (String) parentContextMap.get("PORT");
			}
			if (parentContextMap.containsKey("DATABASE")) {
				context.DATABASE = (String) parentContextMap.get("DATABASE");
			}
			if (parentContextMap.containsKey("USER_NAME")) {
				context.USER_NAME = (String) parentContextMap.get("USER_NAME");
			}
			if (parentContextMap.containsKey("PASSWORD")) {
				context.PASSWORD = (String) parentContextMap.get("PASSWORD");
			}
			if (parentContextMap.containsKey("SERVICE_ACCOUNT")) {
				context.SERVICE_ACCOUNT = (String) parentContextMap
						.get("SERVICE_ACCOUNT");
			}
			if (parentContextMap.containsKey("KEY_FILE")) {
				context.KEY_FILE = (String) parentContextMap.get("KEY_FILE");
			}
			if (parentContextMap.containsKey("PROFILE_ID")) {
				context.PROFILE_ID = (String) parentContextMap
						.get("PROFILE_ID");
			}
			if (parentContextMap.containsKey("GAPROFILE_ID")) {
				context.GAPROFILE_ID = (String) parentContextMap
						.get("GAPROFILE_ID");
			}
			if (parentContextMap.containsKey("LOG_FILE_DIR")) {
				context.LOG_FILE_DIR = (String) parentContextMap
						.get("LOG_FILE_DIR");
			}
			if (parentContextMap.containsKey("CURRENT_DATE")) {
				context.CURRENT_DATE = (String) parentContextMap
						.get("CURRENT_DATE");
			}
			if (parentContextMap.containsKey("DynamicFetch_AdditionalParams")) {
				context.DynamicFetch_AdditionalParams = (String) parentContextMap
						.get("DynamicFetch_AdditionalParams");
			}
			if (parentContextMap.containsKey("DynamicFetch_Login")) {
				context.DynamicFetch_Login = (String) parentContextMap
						.get("DynamicFetch_Login");
			}
			if (parentContextMap.containsKey("DynamicFetch_Database")) {
				context.DynamicFetch_Database = (String) parentContextMap
						.get("DynamicFetch_Database");
			}
			if (parentContextMap.containsKey("DynamicFetch_Password")) {
				context.DynamicFetch_Password = (java.lang.String) parentContextMap
						.get("DynamicFetch_Password");
			}
			if (parentContextMap.containsKey("DynamicFetch_Server")) {
				context.DynamicFetch_Server = (String) parentContextMap
						.get("DynamicFetch_Server");
			}
			if (parentContextMap.containsKey("DynamicFetch_Port")) {
				context.DynamicFetch_Port = (String) parentContextMap
						.get("DynamicFetch_Port");
			}
		}

		// Resume: init the resumeUtil
		resumeEntryMethodName = ResumeUtil
				.getResumeEntryMethodName(resuming_checkpoint_path);
		resumeUtil = new ResumeUtil(resuming_logs_dir_path, isChildJob, rootPid);
		resumeUtil.initCommonInfo(pid, rootPid, fatherPid, projectName,
				jobName, contextStr, jobVersion);

		// Resume: jobStart
		resumeUtil.addLog("JOB_STARTED", "JOB:" + jobName,
				parent_part_launcher, Thread.currentThread().getId() + "", "",
				"", "", "", resumeUtil.convertToJsonText(context));

		java.util.concurrent.ConcurrentHashMap<Object, Object> concurrentHashMap = new java.util.concurrent.ConcurrentHashMap<Object, Object>();
		globalMap.put("concurrentHashMap", concurrentHashMap);

		long startUsedMemory = Runtime.getRuntime().totalMemory()
				- Runtime.getRuntime().freeMemory();
		long endUsedMemory = 0;
		long end = 0;

		startTime = System.currentTimeMillis();

		this.globalResumeTicket = true;// to run tPreJob

		this.globalResumeTicket = false;// to run others jobs

		try {
			errorCode = null;
			tJava_1Process(globalMap);
			if (!"failure".equals(status)) {
				status = "end";
			}
		} catch (TalendException e_tJava_1) {

			e_tJava_1.printStackTrace();
			globalMap.put("tJava_1_SUBPROCESS_STATE", -1);

		}

		this.globalResumeTicket = true;// to run tPostJob

		end = System.currentTimeMillis();

		if (watch) {
			System.out.println((end - startTime) + " milliseconds");
		}

		endUsedMemory = Runtime.getRuntime().totalMemory()
				- Runtime.getRuntime().freeMemory();
		if (false) {
			System.out
					.println((endUsedMemory - startUsedMemory)
							+ " bytes memory increase when running : Dymanically_Fetching_GA_Data");
		}

		int returnCode = 0;
		if (errorCode == null) {
			returnCode = status != null && status.equals("failure") ? 1 : 0;
		} else {
			returnCode = errorCode.intValue();
		}
		resumeUtil.addLog("JOB_ENDED", "JOB:" + jobName, parent_part_launcher,
				Thread.currentThread().getId() + "", "", "" + returnCode, "",
				"", "");

		return returnCode;

	}

	public void destroy() {

	}

	private java.util.Map<String, Object> getSharedConnections4REST() {
		java.util.Map<String, Object> connections = new java.util.HashMap<String, Object>();
		return connections;
	}

	private void evalParam(String arg) {
		if (arg.startsWith("--resuming_logs_dir_path")) {
			resuming_logs_dir_path = arg.substring(25);
		} else if (arg.startsWith("--resuming_checkpoint_path")) {
			resuming_checkpoint_path = arg.substring(27);
		} else if (arg.startsWith("--parent_part_launcher")) {
			parent_part_launcher = arg.substring(23);
		} else if (arg.startsWith("--watch")) {
			watch = true;
		} else if (arg.startsWith("--stat_port=")) {
			String portStatsStr = arg.substring(12);
			if (portStatsStr != null && !portStatsStr.equals("null")) {
				portStats = Integer.parseInt(portStatsStr);
			}
		} else if (arg.startsWith("--trace_port=")) {
			portTraces = Integer.parseInt(arg.substring(13));
		} else if (arg.startsWith("--client_host=")) {
			clientHost = arg.substring(14);
		} else if (arg.startsWith("--context=")) {
			contextStr = arg.substring(10);
			isDefaultContext = false;
		} else if (arg.startsWith("--father_pid=")) {
			fatherPid = arg.substring(13);
		} else if (arg.startsWith("--root_pid=")) {
			rootPid = arg.substring(11);
		} else if (arg.startsWith("--father_node=")) {
			fatherNode = arg.substring(14);
		} else if (arg.startsWith("--pid=")) {
			pid = arg.substring(6);
		} else if (arg.startsWith("--context_param")) {
			String keyValue = arg.substring(16);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.put(keyValue.substring(0, index),
							replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.put(keyValue.substring(0, index),
							keyValue.substring(index + 1));
				}
			}
		}

	}

	private final String[][] escapeChars = { { "\\n", "\n" }, { "\\'", "\'" },
			{ "\\r", "\r" }, { "\\f", "\f" }, { "\\b", "\b" }, { "\\t", "\t" },
			{ "\\\\", "\\" } };

	private String replaceEscapeChars(String keyValue) {
		if (keyValue == null || ("").equals(keyValue.trim())) {
			return keyValue;
		}
		for (String[] strArray : escapeChars) {
			keyValue = keyValue.replace(strArray[0], strArray[1]);
		}
		return keyValue;
	}

	public Integer getErrorCode() {
		return errorCode;
	}

	public String getStatus() {
		return status;
	}

	ResumeUtil resumeUtil = null;
}
/************************************************************************************************
 * 104982 characters generated by Talend Open Studio for Data Integration on the
 * 12 August 2013 13:48:01 IST
 ************************************************************************************************/
